import {loadQuestions,grammarTopics} from './questions.js';
import {unit1Questions,boosterSections} from './booster.js';
import {unit2Questions,unit2Sections} from './booster-unit2.js';
import {spanishGloss} from './translations.js';
import {loadProgress,saveProgress,recordAnswer,resetAll} from './progress.js';
import {renderDashboard,renderStatistics} from './statistics.js';

let questions=[],allQuestions=[],sessionQuestions=[],state=loadProgress(),currentIndex=0,currentSelection=[],selectedChoice='',questionStarted=Date.now(),answered=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];

async function init(){applyPreferences();bindNavigation();bindPractice();try{questions=await loadQuestions();allQuestions=[...questions,...unit1Questions,...unit2Questions];sessionQuestions=[...allQuestions];populateFilters();renderLibrary();renderBooster();renderDashboard(state,allQuestions.length);showView(location.hash.slice(1)||'dashboard');window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'dashboard'))}catch(error){document.querySelector('.main').innerHTML=`<section class="empty-view active"><h2>Question bank unavailable</h2><p>${error.message}. Make sure the data folder is published.</p></section>`}}
function bindNavigation(){$$('.nav-item').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;navigate(a==='continue'?'practice':a)}));$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#themeToggle').addEventListener('click',toggleTheme);$('#soundToggle').addEventListener('click',toggleSound);$('#exitPractice').addEventListener('click',()=>navigate('dashboard'));$('#resetProgress').addEventListener('click',()=>{if(confirm('Reset all locally saved progress?')){state=resetAll();renderDashboard(state,questions.length);renderStatistics(state);toast('Progress reset')}})}
function navigate(view){location.hash=view;showView(view)}
function showView(view){const valid=['dashboard','practice','booster','mock','statistics','library'].includes(view)?view:'dashboard';$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${valid}View`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===valid));$('#pageTitle').textContent={dashboard:'Dashboard',practice:'Practice Session',booster:'C2 Booster',mock:'Mock Exam',statistics:'Statistics',library:'Grammar Library'}[valid];$('#sidebar').classList.remove('open');if(valid==='practice')renderQuestion();if(valid==='statistics')renderStatistics(state);if(valid==='dashboard')renderDashboard(state,allQuestions.length)}
function bindPractice(){$('#checkAnswer').addEventListener('click',checkAnswer);$('#nextQuestion').addEventListener('click',()=>{currentIndex=(currentIndex+1)%sessionQuestions.length;renderQuestion()});$('#resetQuestion').addEventListener('click',()=>{currentSelection=[];selectedChoice='';renderInteraction(sessionQuestions[currentIndex])});$('#applyFilters').addEventListener('click',applyFilters)}
function populateFilters(){const categories=[...new Set(allQuestions.map(q=>q.category))].sort();$('#categoryFilter').innerHTML='<option value="ALL">All categories</option>'+categories.map(c=>`<option>${c}</option>`).join('')}
function applyFilters(){const exam=$('#examFilter').value,category=$('#categoryFilter').value,mode=$('#modeFilter').value;sessionQuestions=allQuestions.filter(q=>(exam==='ALL'||q.exam===exam)&&(category==='ALL'||q.category===category)&&(mode==='ALL'||q.mode===mode));if(!sessionQuestions.length){toast('No exercises match these filters');return}currentIndex=0;renderQuestion();toast(`${sessionQuestions.length} exercises loaded`)}
function instructionFor(q){
  if(q.mode==='build')return 'Build a sentence with the same meaning using the key word.';
  if(q.category==='Prepositions')return 'Choose the correct preposition.';
  if(q.category==='Phrasal Verbs')return 'Choose the correct phrasal verb to complete the sentence.';
  if(q.category==='Collocations')return 'Choose the word or expression that forms the correct collocation.';
  if(q.category==='Idioms'||q.category==='Fixed Expressions')return 'Choose the expression that best completes the sentence.';
  if(q.category==='Word Formation')return 'Choose the correct form of the word in capitals.';
  if(q.category==='Multiple-choice Cloze')return 'Choose the option that best fits the gap.';
  if(q.category==='Open Cloze')return 'Choose the word that best fits the gap.';
  if(q.track==='Vocabulary')return 'Choose the word or expression that best completes the sentence.';
  return 'Choose the option that best completes the sentence.';
}
function renderQuestion(){const q=sessionQuestions[currentIndex];answered=false;currentSelection=[];selectedChoice='';questionStarted=Date.now();$('#questionCounter').textContent=`Question ${currentIndex+1} of ${sessionQuestions.length}`;$('#practiceProgress').style.width=`${(currentIndex+1)/sessionQuestions.length*100}%`;$('#examBadge').textContent=q.exam;$('#cefrBadge').textContent=q.cefr;$('#modeBadge').textContent=q.mode==='build'?'BUILD THE SENTENCE':'MULTIPLE CHOICE';$('#instruction').textContent=instructionFor(q);$('#sourceSentence').textContent=q.source;$('#keyword').textContent=q.keyword||'';$('#keywordLine').hidden=!q.keyword;$('#feedback').hidden=true;$('#nextQuestion').hidden=true;$('#checkAnswer').hidden=false;renderInteraction(q)}
function renderInteraction(q){const area=$('#interactionArea');if(q.mode==='build'){area.innerHTML='<div class="answer-zone" id="answerZone"></div><div class="word-bank" id="wordBank"></div>';q.tokens.forEach((word,i)=>{const b=document.createElement('button');b.className=`word-card ${currentSelection.includes(i)?'used':''}`;b.textContent=word;b.onclick=()=>{currentSelection.push(i);renderInteraction(q)};$('#wordBank').append(b)});currentSelection.forEach((i,pos)=>{const b=document.createElement('button');b.className='word-card';b.textContent=q.tokens[i];b.onclick=()=>{currentSelection.splice(pos,1);renderInteraction(q)};$('#answerZone').append(b)})}else{area.innerHTML='<div class="choice-list" id="choiceList"></div>';q.choices.forEach(choice=>{const b=document.createElement('button'),gloss=q.track==='Vocabulary'?spanishGloss(choice):'';b.className=`choice-card ${gloss?'has-translation':''} ${selectedChoice===choice?'selected':''}`;if(gloss){const en=document.createElement('span'),es=document.createElement('span');en.className='choice-english';en.textContent=choice;es.className='choice-translation';const tag=document.createElement('small');tag.textContent='ES';es.append(tag,document.createTextNode(gloss));b.append(en,es)}else b.textContent=choice;b.onclick=()=>{selectedChoice=choice;renderInteraction(q)};$('#choiceList').append(b)})}}
function checkAnswer(){if(answered)return;const q=sessionQuestions[currentIndex];const response=q.mode==='build'?currentSelection.map(i=>q.tokens[i]).join(' '):selectedChoice;if(!response){toast('Choose an answer first');return}const normalize=s=>s.toLowerCase().replace(/[.,’']/g,'').replace(/\s+/g,' ').trim();const correct=normalize(response)===normalize(q.answer);answered=true;recordAnswer(state,q,correct,Math.max(1,Math.round((Date.now()-questionStarted)/1000)));const fb=$('#feedback');fb.hidden=false;fb.className=`feedback ${correct?'correct':'incorrect'}`;fb.innerHTML=`<strong>${correct?'✓ Correct!':'✕ Not quite'}</strong><span><b>Answer:</b> ${q.answer}</span><span><b>Rule:</b> ${q.rule}. ${q.explanation}</span><span><b>Common error:</b> ${q.commonError}</span>`;$('#checkAnswer').hidden=true;$('#nextQuestion').hidden=false;renderDashboard(state,allQuestions.length);playTone(correct)}
function renderLibrary(){$('#libraryGrid').innerHTML=grammarTopics.map(([title,text,level])=>`<article class="library-card"><span>${level}</span><h3>${title}</h3><p>${text}</p><button class="text-button" data-topic="${title}">Practise topic →</button></article>`).join('');$$('[data-topic]').forEach(b=>b.onclick=()=>{sessionQuestions=questions.filter(q=>q.category===b.dataset.topic);currentIndex=0;navigate('practice')})}
function renderBooster(){
  $('#boosterTracks').innerHTML=boosterSections.map(section=>`<article class="booster-track"><span>${section.count} ITEMS</span><h3>${section.track}</h3><p>${section.description}</p><button class="button primary" data-booster-track="${section.track}">Practise ${section.track}</button></article>`).join('');
  $('#boosterTracks2').innerHTML=unit2Sections.map(section=>`<article class="booster-track"><span>${section.count} ITEMS</span><h3>${section.track}</h3><p>${section.description}</p><button class="button primary" data-booster2-track="${section.track}">Practise ${section.track}</button></article>`).join('');
  $$('[data-booster-track]').forEach(button=>button.onclick=()=>startBooster(button.dataset.boosterTrack,'01'));
  $$('[data-booster2-track]').forEach(button=>button.onclick=()=>startBooster(button.dataset.booster2Track,'02'));
  $('#startFullUnit').onclick=()=>startBooster('ALL','01');
  $('#startFullUnit2').onclick=()=>startBooster('ALL','02');
}
function startBooster(track,unit='01'){const bank=unit==='02'?unit2Questions:unit1Questions;sessionQuestions=track==='ALL'?[...bank]:bank.filter(q=>q.track===track);currentIndex=0;navigate('practice');toast(`${sessionQuestions.length} Unit ${unit} exercises loaded`)}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';applyPreferences();saveProgress(state)}function toggleSound(){state.sound=!state.sound;applyPreferences();saveProgress(state)}function applyPreferences(){document.documentElement.dataset.theme=state.theme;$('#themeToggle').innerHTML=`${state.theme==='dark'?'☀':'☾'} <span>${state.theme==='dark'?'Light':'Dark'} mode</span>`;$('#soundToggle').innerHTML=`${state.sound?'♫':'⊘'} <span>Sound ${state.sound?'on':'off'}</span>`}function playTone(correct){if(!state.sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=correct?620:180;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.18)}catch{}}function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
init();
