// C2 Booster - Unit 05
// Original C2 practice based on the unit skill map: Reported Speech,
// Education & Learning, and English in Use. No book exercise is reproduced.

function tokens(answer,seed){return answer.replace(/[.?!]$/,'').split(/\s+/).map((word,i)=>({word,n:(i*47+seed*31)%137})).sort((a,b)=>a.n-b.n).map(x=>x.word)}
function q(id,activity,track,category,source,choices,answer,rule,keyword='',glosses={}){const mode=keyword?'build':'choice';return{id:'b5-'+id,exam:'BOOSTER',cefr:'C2',unit:'Unit 05',activity,track,category,mode,source,keyword,answer:answer.replace(/[.?!]$/,''),choices,tokens:tokens(answer,Number(id.replace(/\D/g,''))||1),rule,glosses,explanation:`This item practises ${rule}.`,commonError:'Check the reporting time, pronouns, reference words, verb pattern and exact meaning.',miniLesson:'Reported speech reshapes a message according to viewpoint, time and the reporting verb selected.'}}
function addChoices(prefix,activity,track,category,items){items.forEach(([source,choices,answer,rule],i)=>unit5Questions.push(q(prefix+String(i+1).padStart(2,'0'),activity,track,category,source,choices,answer,rule)))}
function addBuilds(prefix,activity,track,category,items){items.forEach(([source,keyword,answer,rule],i)=>unit5Questions.push(q(prefix+String(i+1).padStart(2,'0'),activity,track,category,source,[],answer,rule,keyword)))}
export const unit5Questions=[];

// GRAMMAR - 80 items.
addChoices('g1-','Grammar 1 - Reporting messages','Grammar','Reported Speech',[
 ['“I submitted the revised draft yesterday,” Mara said. Mara said she ___ the revised draft the previous day.',['had submitted','submitted tomorrow','has been submitting','would submit yesterday'],'had submitted','past perfect backshift and changed time reference'],
 ['“I will contact the examiner next week,” Leo said. Leo said he ___ the examiner the following week.',['would contact','will have contacted yesterday','had contacted next week','contacts the previous week'],'would contact','future in the past'],
 ['“Water expands when it freezes,” the lecturer said. The lecturer said water ___ when it freezes.',['expands','had expanded only then','would expand yesterday','was expanding the day before'],'expands','no backshift for a scientific fact'],
 ['“I have never taught online before,” she admitted. She admitted that she ___ online before.',['had never taught','would never teach yesterday','has never teaching','never teaches tomorrow'],'had never taught','present perfect to past perfect backshift'],
 ['“We are reviewing the assessment policy,” they explained. They explained that they ___ the assessment policy.',['were reviewing','had reviewed tomorrow','would reviewing','reviewed next year'],'were reviewing','present continuous to past continuous backshift'],
 ['“The workshop began at nine,” he told us. He told us that the workshop ___ at nine.',['had begun','would begin the following year','has beginning','begins tomorrow'],'had begun','past simple to past perfect backshift'],
 ['“I may postpone the tutorial,” the tutor said. The tutor said she ___ the tutorial.',['might postpone','may postponed yesterday','had postponing','would have postpone'],'might postpone','may to might in reported speech'],
 ['“You must upload the form today,” she told me. She told me I ___ the form that day.',['had to upload','must uploaded tomorrow','would uploading','had uploaded next week'],'had to upload','must to had to for obligation'],
 ['“I can verify the figures now,” Ravi said. Ravi said he ___ the figures then.',['could verify','can verified yesterday','had verifying','would have verify'],'could verify','can to could and now to then'],
 ['“I was waiting outside,” Nina said. Nina said she ___ outside.',['had been waiting','would wait tomorrow','has waited then','was wait yesterday'],'had been waiting','past continuous to past perfect continuous'],
 ['“I ought to apologise,” he said. He said he ___ apologise.',['ought to','had ought','would ought to','oughted to'],'ought to','unchanged modal ought to'],
 ['“I would prefer a later seminar,” Jo said. Jo said she ___ a later seminar.',['would prefer','had preferred tomorrow','will prefer yesterday','would preferred'],'would prefer','unchanged would in reported speech'],
 ['“I am meeting the dean tonight,” Ana said. Ana said she ___ the dean that night.',['was meeting','had met tomorrow night','would meeting','is meet the previous night'],'was meeting','backshift and changed time expression'],
 ['“The students have been working here since March,” he said. He said the students ___ there since March.',['had been working','would work here tomorrow','have been worked','were work there'],'had been working','perfect continuous backshift and place reference'],
 ['“I saw her two days ago,” Kim said on Friday. Kim said she had seen her ___.',['two days before','in two days','the following weekend','tomorrow morning'],'two days before','ago to before in reported speech'],
 ['“This module ends tomorrow,” the coordinator said. The coordinator said that ___ module ended the next day.',['that','this here','these','the following this'],'that','demonstrative change this to that'],
 ['“These notes belong to me,” Ivo said. Ivo said ___ notes belonged to him.',['those','these here','this','that ones'],'those','demonstrative and pronoun shift'],
 ['“I am staying here until Friday,” Bea said. Bea said she was staying ___ until Friday.',['there','here tomorrow','this place yesterday','then here'],'there','place adverb change'],
 ['“The results arrived this morning,” he said that evening. He said the results had arrived ___.',['that morning','the following morning','tomorrow morning','the previous night'],'that morning','this to that in a time phrase'],
 ['“I need not attend tomorrow,” she said. She said she ___ attend the following day.',['did not need to','must not attended','would not needing to','had not attend'],'did not need to','need not to did not need to']
]);

addBuilds('g2-','Grammar 2 - Direct to reported transformations','Grammar','Reported Speech',[
 ['“Are you attending the symposium?” she asked me.','WHETHER','She asked me whether I was attending the symposium','reported yes-no question'],
 ['“Where did you store the recordings?” he asked us.','WHERE','He asked us where we had stored the recordings','reported wh-question with statement order'],
 ['“Please submit the form by noon,” the administrator said.','ASKED','The administrator asked us to submit the form by noon','ask plus object plus infinitive'],
 ['“Do not disclose your candidate number,” the invigilator said.','WARNED','The invigilator warned us not to disclose our candidate numbers','negative infinitive after warn'],
 ['“Why don’t we revise together?” Carla said.','SUGGESTED','Carla suggested revising together','suggest plus gerund'],
 ['“Shall I print another copy for you?” he said.','OFFERED','He offered to print another copy for me','offer plus infinitive'],
 ['“I definitely did not alter the data,” the researcher said.','DENIED','The researcher denied having altered the data','deny plus perfect gerund'],
 ['“Yes, I used an unauthorised source,” the candidate said.','ADMITTED','The candidate admitted using an unauthorised source','admit plus gerund'],
 ['“You really should request feedback,” my mentor said.','ADVISED','My mentor advised me to request feedback','advise plus object plus infinitive'],
 ['“I will certainly return the books tomorrow,” he said.','PROMISED','He promised to return the books the following day','promise plus infinitive'],
 ['“No, I will not extend the deadline,” the lecturer said.','REFUSED','The lecturer refused to extend the deadline','refuse plus infinitive'],
 ['“If you publish that claim, I will sue you,” she said.','THREATENED','She threatened to sue me if I published that claim','threaten plus infinitive'],
 ['“Remember to cite the original study,” the supervisor said.','REMINDED','The supervisor reminded me to cite the original study','remind plus object plus infinitive'],
 ['“You copied entire paragraphs from my essay,” Liam said to Ava.','ACCUSED','Liam accused Ava of copying entire paragraphs from his essay','accuse plus object plus of plus gerund'],
 ['“I am sorry I interrupted your presentation,” she said.','APOLOGISED','She apologised for interrupting my presentation','apologise for plus gerund'],
 ['“The online portal will be unavailable tonight,” the technician told us.','INFORMED','The technician informed us that the online portal would be unavailable that night','inform plus object plus that clause'],
 ['“You must reconsider the marking criteria,” they told the board.','INSISTED','They insisted that the board reconsider the marking criteria','formal subjunctive after insist'],
 ['“Let me carry those reference books,” Omar said.','OFFERED','Omar offered to carry the reference books','offer to do something'],
 ['“What time does the library close?” she asked.','KNEW','She wanted to know what time the library closed','indirect question with statement order'],
 ['“Could you explain the final paragraph again?” I asked.','TO','I asked the tutor to explain the final paragraph again','request reported with ask plus infinitive']
]);

addChoices('g3-','Grammar 3 - Reporting verb patterns','Grammar','Verb Patterns',[
 ['The dean ___ students that several rooms would be unavailable.',['informed','explained students','said students','informed to'],'informed','inform plus object plus that clause'],
 ['The witness ___ having seen the confidential document.',['denied','refused that','explained to see','informed seeing'],'denied','deny plus gerund'],
 ['The tutor ___ that we take a short break.',['recommended','advised us that to','suggested us to','offered us taking'],'recommended','recommend plus subjunctive that clause'],
 ['The chair ___ to postpone the vote until everyone was present.',['agreed','encouraged','reminded','accused'],'agreed','agree plus infinitive'],
 ['The laboratory assistant ___ us not to touch the samples.',['warned','denied','complained','suggested'],'warned','warn plus object plus infinitive'],
 ['The student ___ for having submitted the assignment late.',['apologised','admitted us','insisted us','explained us'],'apologised','apologise for plus perfect gerund'],
 ['My supervisor ___ me to narrow the research question.',['encouraged','suggested','complained','claimed'],'encouraged','encourage plus object plus infinitive'],
 ['The candidate ___ that the ambiguous wording had confused her.',['complained','refused','offered','encouraged'],'complained','complain plus that clause'],
 ['The examiner ___ allowing candidates five extra minutes.',['suggested','advised them that to','offered them for','reminded allowing'],'suggested','suggest plus gerund'],
 ['The publisher ___ to withdraw the inaccurate edition.',['promised','accused','recommended us','warned that us'],'promised','promise plus infinitive'],
 ['The committee ___ the applicant of falsifying a certificate.',['accused','denied','claimed','informed to'],'accused','accuse plus object plus of plus gerund'],
 ['The professor ___ to have identified a flaw in the theory.',['claimed','informed','suggested','apologised'],'claimed','claim plus perfect infinitive'],
 ['The school ___ parents from removing children during examinations.',['discouraged','denied','offered','explained'],'discouraged','discourage plus object plus from plus gerund'],
 ['The researcher ___ on checking every source personally.',['insisted','advised','warned','offered'],'insisted','insist on plus gerund'],
 ['The librarian ___ me that my loan period was about to expire.',['reminded','explained to','said','suggested to'],'reminded','remind plus object plus that clause'],
 ['The director ___ that no staff member had leaked the report.',['maintained','advised to us','informed','offered'],'maintained','maintain plus that clause'],
 ['The student representative ___ to the dean about being excluded.',['complained','denied','suggested','refused'],'complained','complain to somebody about gerund'],
 ['The lecturer ___ us to compare the two theoretical models.',['instructed','suggested','claimed','denied'],'instructed','instruct plus object plus infinitive'],
 ['The board ___ that the policy be reviewed immediately.',['demanded','offered','apologised','encouraged us'],'demanded','demand plus subjunctive that clause'],
 ['She ___ being responsible for the discrepancy.',['admitted','informed to','explained us','refused that'],'admitted','admit plus gerund']
]);

addBuilds('g4-','Grammar 4 - Advanced reporting','Grammar','Advanced Structures',[
 ['“You must attend at least eighty per cent of the seminars,” the coordinator told us.','REQUIRED','The coordinator said that we were required to attend at least eighty per cent of the seminars','reporting an obligation with passive requirement'],
 ['“I might have misinterpreted the statistics,” the analyst said.','CONCEDED','The analyst conceded that she might have misinterpreted the statistics','concede plus modal perfect clause'],
 ['“Under no circumstances should you reveal the password,” he said.','EMPHASISED','He emphasised that under no circumstances should we reveal the password','reporting an emphatic prohibition'],
 ['“I did not realise the source was unreliable,” Marta said.','CLAIMED','Marta claimed not to have realised that the source was unreliable','negative perfect infinitive after claim'],
 ['“Let us establish an independent review panel,” the union said.','PROPOSED','The union proposed that an independent review panel be established','propose plus passive subjunctive'],
 ['“Had I known about the error, I would have corrected it,” he said.','EXPLAINED','He explained that he would have corrected the error if he had known about it','reported third conditional'],
 ['“You may use a bilingual dictionary,” the examiner told us.','PERMITTED','The examiner said that we were permitted to use a bilingual dictionary','reported permission with passive verb'],
 ['“I wish I had taken detailed notes,” Paula said.','REGRETTED','Paula regretted not having taken detailed notes','regret plus perfect gerund'],
 ['“The findings may have been overstated,” the reviewer said.','SUGGESTED','The reviewer suggested that the findings might have been overstated','reported modal perfect passive'],
 ['“I expect every student to participate,” the lecturer said.','MADE','The lecturer made it clear that every student was expected to participate','reporting through a fixed expression'],
 ['“Why was the control group excluded?” the editor asked.','WANTED','The editor wanted to know why the control group had been excluded','reported passive question'],
 ['“You would be better off revising the conclusion,” she told me.','URGED','She urged me to revise the conclusion','urge plus object plus infinitive'],
 ['“Nobody told me that the venue had changed,” Ravi said.','COMPLAINED','Ravi complained that nobody had told him the venue had changed','complain plus that clause'],
 ['“I can assure you that the marking was impartial,” she said.','ASSURED','She assured us that the marking had been impartial','assure plus object plus that clause'],
 ['“It was Alex who deleted the recording,” Mia said.','BLAMED','Mia blamed Alex for deleting the recording','blame plus object plus for plus gerund'],
 ['“Do not assume that correlation proves causation,” the professor said.','CAUTIONED','The professor cautioned us against assuming that correlation proved causation','caution against plus gerund'],
 ['“I will resign unless the decision is reversed,” the director said.','THREATENED','The director threatened to resign unless the decision was reversed','threaten plus infinitive and reported conditional'],
 ['“Yes, the department failed to consult students,” the dean said.','ACKNOWLEDGED','The dean acknowledged that the department had failed to consult students','acknowledge plus that clause'],
 ['“Please do not quote me directly,” the researcher said.','REQUESTED','The researcher requested that she not be quoted directly','request plus passive subjunctive'],
 ['“The evidence unquestionably supports our conclusion,” they said.','MAINTAINED','They maintained that the evidence unquestionably supported their conclusion','maintain plus that clause']
]);

// VOCABULARY - Education & Learning, 129 items.
function lexical(prefix,activity,category,entries){const glosses=Object.fromEntries(entries.map(([w,es])=>[w,es]));const pool=[...new Set(entries.map(([w])=>w))];entries.forEach(([answer,,source],i)=>{const alternatives=pool.filter(w=>w!==answer);const choices=[answer,...[1,3,5].map(step=>alternatives[(i+step)%alternatives.length])];unit5Questions.push(q(prefix+String(i+1).padStart(2,'0'),activity,'Vocabulary',category,source,choices,answer,`precise ${category.toLowerCase()} usage`,'',glosses))})}
lexical('v1-','Vocabulary 1 - Education nouns','Education & Learning',[
 ['attendance','asistencia','Regular ___ is essential because each seminar builds on the previous one.'],['dissertation','tesis / disertación','Her doctoral ___ examines bilingual identity in border communities.'],['syllabus','programa de estudios','The revised ___ includes assessment criteria and weekly learning outcomes.'],['orientation','orientación / inducción','New students attend an online ___ before classes begin.'],['workshop','taller','The faculty organised a practical ___ on academic writing.'],['scholar','académico / erudito','She is widely regarded as the leading ___ in medieval linguistics.'],['literacy','alfabetización / competencia lectora','Digital ___ involves evaluating online information critically.'],['faculty','facultad / personal académico','The ___ approved a new interdisciplinary degree.'],['discipline','disciplina / conducta','The school replaced punitive ___ with restorative conversations.'],['scholarship','beca','A merit-based ___ covered his tuition and accommodation.'],['schooling','escolarización','Interrupted ___ can have long-term social consequences.'],['first','calificación de primera clase','She graduated with a ___ in chemical engineering.'],['curriculum','currículo','Climate education has been incorporated into the national ___.']
]);
lexical('v2-','Vocabulary 2 - Education verbs','Education & Learning',[
 ['enrol','matricular(se)','International applicants must ___ before the registration deadline.'],['expel','expulsar','A school may ___ a pupil only after a formal disciplinary process.'],['invigilate','vigilar un examen','Two independent staff members will ___ the final examination.'],['flunk','reprobar','Even capable learners can ___ an exam if anxiety overwhelms them.'],['instruct','instruir / enseñar','The handbook will ___ candidates on how to submit evidence.'],['commit','memorizar / encomendar','Retrieval practice helps learners ___ new vocabulary to memory.'],['resit','volver a rendir','Students who narrowly fail may ___ the paper in September.'],['admit','admitir / aceptar','The programme will ___ only thirty candidates this year.'],['skip','saltarse','Learners who regularly ___ lessons often struggle to catch up.']
]);
lexical('v3-','Vocabulary 3 - Education adjectives','Education & Learning',[
 ['comprehensive','integral / exhaustivo','The course offers a ___ introduction to research methods.'],['curricular','curricular','Assessment objectives must remain aligned with ___ priorities.'],['extracurricular','extracurricular','Debating clubs provide valuable ___ learning opportunities.'],['literate','alfabetizado / competente','Citizens need to be scientifically ___ to assess health claims.'],['studious','estudioso','Despite appearing carefree, he is remarkably ___ before examinations.'],['tertiary','superior / universitario','Access to ___ education has expanded considerably.'],['well-educated','bien educado / con buena formación','The region has a highly ___ and multilingual workforce.']
]);
lexical('v4-','Vocabulary 4 - Education phrasal verbs','Phrasal Verbs',[
 ['drop out','abandonar los estudios','Financial pressure forced her to ___ of university temporarily.'],['take on','asumir','Avoid trying to ___ more coursework than you can manage.'],['get away with','salirse con la suya','Students should not expect to ___ plagiarism.'],['keep to yourself','guardarse para uno mismo','Do not ___ a useful revision strategy; share it with the group.'],['miss out on','perderse','Learners without internet access may ___ valuable resources.'],['settle in','adaptarse','It took him several weeks to ___ at the residential college.'],['set off','provocar','The teacher’s unexpected demonstration ___ a lively debate.'],['take in','asimilar / comprender','The lecture was so dense that I could barely ___ the main argument.'],['check up on','comprobar cómo está','The tutor called to ___ a student who had missed several classes.'],['give in','entregar / ceder','Remember to ___ your portfolio before Friday.'],['associate with','relacionarse con','The institute encourages researchers to ___ colleagues overseas.'],['mess around','perder el tiempo / tontear','Some pupils continued to ___ instead of completing the experiment.'],['leap at','aceptar con entusiasmo','She ___ the chance to study abroad for a semester.']
]);
lexical('v5-','Vocabulary 5 - Education prepositions','Prepositions',[
 ['for','para','Applicants from low-income households may be eligible ___ a full grant.'],['for','hacia','The children made a dash ___ the bus when the bell rang.'],['in','en','His complete absorption ___ the project made him lose track of time.'],['from','de','Persistent bullying can result in exclusion ___ school.'],['in','en','The department offers specialist courses ___ forensic linguistics.'],['for','para / hacia','She is studying ___ a postgraduate diploma in counselling.'],['into','en / dentro de','Critical media skills should be incorporated ___ every subject.'],['with','con','The programme equips teachers ___ practical assessment tools.'],['through','mediante','The school tackled low motivation ___ collaborative projects.'],['to','a','Candidates are advised to apply ___ several universities.']
]);
lexical('v6-','Vocabulary 6 - Academic collocations','Collocations',[
 ['apply to university','postular a la universidad','Most pupils begin to ___ during their final school year.'],['submit an application','presentar una solicitud','You must ___ through the central admissions portal.'],['take a course','llevar un curso','I decided to ___ in corpus linguistics.'],['do a course','hacer un curso','She plans to ___ online while working full time.'],['flunk a course','reprobar un curso','Poor attendance can cause an otherwise capable student to ___.'],['come prepared','venir preparado','Participants are expected to ___ with two discussion questions.'],['pay attention','prestar atención','It is difficult to ___ when a lecture lacks structure.'],['make a presentation','hacer una presentación','Each group will ___ on an educational innovation.'],['do research','realizar investigación','Postgraduates are encouraged to ___ across disciplinary boundaries.'],['take an exam','rendir un examen','Candidates may ___ at an authorised centre.'],['flunk an exam','reprobar un examen','One weak result does not mean you will ___ again.'],['sit an exam','presentarse a un examen','More than five hundred learners will ___ this weekend.'],['resit an exam','volver a rendir un examen','You can ___ during the summer assessment period.'],['get good marks','obtener buenas notas','Understanding criteria helps students ___.'],['get a degree','obtener un título','She hopes to ___ in environmental science.'],['give a lecture','dictar una conferencia','A visiting economist will ___ on global inequality.'],['evaluate progress','evaluar el progreso','Short diagnostic tasks help teachers ___.'],['grade assignments','calificar tareas','Tutors use a shared rubric to ___.'],['evaluate assignments','evaluar tareas','Peer review can help learners ___ critically.'],['make an exception','hacer una excepción','The board refused to ___ to the attendance rule.'],['meet a deadline','cumplir un plazo','Planning backwards makes it easier to ___.'],['earn a qualification','obtener una certificación','The apprenticeship enables participants to ___.'],['deliver a seminar','dictar un seminario','Two doctoral students will ___ on language policy.'],['conduct an experiment','realizar un experimento','The class will ___ under controlled conditions.']
]);
lexical('v7-','Vocabulary 7 - Education idioms','Idioms',[
 ['make common cause','unir fuerzas','Teachers and parents decided to ___ over school funding.'],['down in the mouth','decaído','He has looked ___ since receiving his examination result.'],['out of hand','sin considerarlo','Innovative proposals should not be dismissed ___.'],['in leaps and bounds','a pasos agigantados','Her academic English has improved ___.'],['stand a good chance','tener buenas posibilidades','Well-prepared applicants ___ of obtaining a place.'],['stuck in a rut','estancado en la rutina','After teaching the same module for years, he felt ___.'],['bend the rules','flexibilizar las reglas','The principal agreed to ___ in an exceptional case.'],['all Greek to me','incomprensible para mí','The statistical notation was ___.'],['lose heart','desanimarse','Do not ___ if your first draft receives extensive feedback.'],['go with the flow','adaptarse a las circunstancias','Experienced teachers can ___ when technology fails.'],['start the ball rolling','poner algo en marcha','A student question helped ___ on the class debate.'],['left to their own devices','dejados a su propio criterio','The learners became more resourceful when ___.'],['beyond your wildest dreams','más allá de tus mejores sueños','The scholarship opened opportunities ___.'],['see eye to eye','estar de acuerdo','The two examiners did not ___ on the final grade.'],['on the spur of the moment','de improviso','The tutor designed the extension activity ___.'],['play truant','faltar a clases sin permiso','Repeatedly choosing to ___ led to disciplinary action.'],['make an educated guess','hacer una suposición fundamentada','Use contextual evidence to ___.'],['draw the line at','poner el límite en','I will help with the bibliography, but I ___ writing the conclusion.']
]);
lexical('v8-','Vocabulary 8 - Academic fixed expressions','Fixed Expressions',[
 ['commit to memory','memorizar','Frequent retrieval helps students ___ complex terminology.'],['at issue','en cuestión','What is ___ is the reliability of the evidence.'],['by means of','por medio de','The researchers collected responses ___ an anonymous survey.'],['at a disadvantage','en desventaja','Learners without quiet study space are ___.'],['make an exception','hacer una excepción','The committee may ___ where compelling evidence exists.'],['be authorised to','estar autorizado a','Only trained staff ___ administer the assessment.'],['on the basis of','basándose en','Places are allocated ___ academic merit and need.'],['a bit of a','un poco / algo de','Returning to study after twenty years was ___ challenge.'],['in any event','en cualquier caso','___, candidates should keep copies of all documents.'],['a prime example','un excelente ejemplo','The project is ___ of successful interdisciplinary learning.'],['deciding factor','factor decisivo','Course flexibility was the ___ in her choice.'],['in line with','de acuerdo con','The revised rubric is ___ national standards.'],['put your mind to','proponerse seriamente','You can master the method if you ___ it.'],['turn your back on','dar la espalda a','Universities must not ___ disadvantaged communities.'],['in the form of','en forma de','Feedback was provided ___ brief audio recordings.']
]);
addBuilds('v9-','Vocabulary 9 - Lexical transformations','Vocabulary','Vocabulary Transformations',[
 ['Everyone was deeply asleep when the alarm sounded.','SOUND','Everyone was sound asleep when the alarm sounded','fixed adjective collocation'],['She cannot decide whether to accept the scholarship.','MINDS','She is in two minds about accepting the scholarship','idiom be in two minds'],['The inaccurate article seriously damaged his academic reputation.','INJURIOUS','The inaccurate article was injurious to his academic reputation','formal adjective transformation'],['The student became extremely angry when accused of cheating.','BESIDE','The student was beside himself with anger when accused of cheating','idiom beside oneself'],['Her failure to attend seminars caused her exclusion.','LED','Her poor attendance led to her exclusion','lead to plus noun'],['The twins look completely identical.','EXACT','Each twin is the exact image of the other','fixed noun expression'],['Although the module was demanding, he completed it successfully.','SPITE','In spite of the demanding module he completed it successfully','concessive fixed expression'],['The supervisor promised that she would provide feedback.','WORD','The supervisor gave her word that she would provide feedback','give your word'],['An occasional day away from revision will not harm you.','NOW','A day away from revision now and then will not harm you','now and then'],['He was offended by the examiner’s dismissive tone.','EXCEPTION','He took exception to the examiner’s dismissive tone','take exception to'],['Tutorials are held every two weeks.','INTERVALS','Tutorials are held at two-week intervals','at intervals'],['The confusing instructions discouraged several candidates.','PUT','Several candidates were put off by the confusing instructions','phrasal passive'],['However severely her thesis was criticised, she remained confident.','AMOUNT','No amount of criticism affected her confidence','no amount of'],['The post requires frequent travel to overseas campuses.','INVOLVES','The post involves travelling frequently to overseas campuses','involve plus gerund'],['What effect will the new policy have on mature students?','IMPLICATIONS','What implications will the new policy have for mature students','have implications for'],['Nobody understands why the lecturer resigned.','MYSTERY','It is a mystery why the lecturer resigned','it is a mystery why'],['The allotted time was not enough to complete the assessment.','INSUFFICIENT','We were given insufficient time to complete the assessment','insufficient plus noun'],['The strike caused the graduation ceremony to be cancelled.','RESULTED','The strike resulted in the graduation ceremony being cancelled','result in plus gerund'],['I briefly saw the dean outside the library.','GLIMPSE','I caught a glimpse of the dean outside the library','catch a glimpse of'],['She attempted the advanced problem but could not solve it.','GO','She had a go at solving the advanced problem','have a go at gerund']
]);

// ENGLISH IN USE - 41 items.
addChoices('e1-','English in Use 1 - Word formation','English in Use','Word Formation',[
 ['The improvement in retention was immediately ___.',['noticeable','noticedly','noticeful','unnoticeably'],'noticeable','adjective formation from notice'],['Academic misconduct can lead to permanent ___.',['disqualification','disqualifying','disqualifiedness','qualifier'],'disqualification','noun formation from disqualify'],['The programme places considerable emphasis on learner ___.',['autonomy','autonomousness','autonomously','autonomist'],'autonomy','abstract noun formation'],['The two accounts are fundamentally ___.',['incompatible','uncompatibly','compatibility','discompatibility'],'incompatible','negative adjective prefix'],['The research team questioned the ___ of the original sample.',['representativeness','representatively','representationable','unrepresent'],'representativeness','abstract noun suffix'],['The committee requested further ___ before reaching a decision.',['clarification','clarifyingly','clarifiedness','clarificative'],'clarification','noun formation from clarify'],['The lecturer’s explanation was admirably ___.',['comprehensive','comprehensivelyness','comprehensioned','incomprehend'],'comprehensive','adjective formation from comprehend'],['The policy has been criticised for reinforcing educational ___.',['inequality','unequalnesses','inequalise','equally'],'inequality','negative noun prefix'],['Her argument was weakened by several factual ___.',['inaccuracies','inaccuratenessly','accuratisms','disaccurate'],'inaccuracies','plural negative noun'],['The qualification is internationally ___.',['recognised','recognitioned','recognisablely','recognisingness'],'recognised','past participle adjective'],['The new assessment system is remarkably ___.',['adaptable','adaptationary','adaptablyness','unadapting'],'adaptable','adjective suffix able'],['Staff expressed strong ___ of the proposed cuts.',['disapproval','unapprovingness','approvement','disapprovedly'],'disapproval','negative noun formation'],['The findings prompted a complete ___ of the theory.',['reconsideration','considerateness','reconsiderably','consideringness'],'reconsideration','prefix and noun suffix'],['Her contribution to the seminar was highly ___.',['meaningful','meaningly','meaningfulnessly','unmeaning'],'meaningful','adjective suffix ful'],['The course encourages intellectual curiosity and ___.',['adventurousness','adventurouslyness','adventured','adventurely'],'adventurousness','abstract noun from adjective']
]);
addBuilds('e2-','English in Use 2 - Key word transformations','English in Use','Advanced Structures',[
 ['The personal nature of the question surprised me completely.','GUARD','I was caught completely off guard by the personal question','catch someone off guard'],['The professor knows a great deal about language assessment.','WIDE','The professor has a wide knowledge of language assessment','wide knowledge of'],['Nobody could understand his behaviour during the viva.','BEYOND','His behaviour during the viva was beyond comprehension','beyond comprehension'],['I regard Professor Ellis as my most influential mentor.','LOOK','I look upon Professor Ellis as my most influential mentor','look upon as'],['Mia will undoubtedly obtain a distinction.','FOREGONE','It is a foregone conclusion that Mia will obtain a distinction','foregone conclusion'],['Even though Leo tried very hard, he could not solve the problem.','MATTER','No matter how hard Leo tried he could not solve the problem','no matter how'],['Only Priya managed to achieve the required score.','FAILED','Everyone except Priya failed to achieve the required score','everyone except'],['You must remain calm during the oral defence.','COOL','You must keep your cool during the oral defence','keep your cool']
]);
addChoices('e3-','English in Use 3 - Multiple-choice cloze','English in Use','Multiple-choice Cloze',[
 ['Retrieval practice plays a central role in the ___ of durable memories.',['formation','manufacture','construction site','fabrication'],'formation','academic noun collocation'],['Working memory is ___ from long-term memory in both capacity and duration.',['distinct','transparent','noticeable of','categorical from'],'distinct','distinct from collocation'],['New information is initially ___ through sensory channels.',['encoded','concealed','translated away','rendered off'],'encoded','technical memory-process verb'],['Relevant knowledge is later ___ from long-term storage.',['retrieved','salvaged up','regained to','restored on'],'retrieved','retrieve information collocation'],['Several theories fall under the broad ___ of cognitive psychology.',['classification','implication to','aspiration','integration at'],'classification','fall under a classification'],['Some learning occurs ___, without deliberate awareness.',['implicitly','decisively','frankly literal','definitively open'],'implicitly','adverb meaning unconsciously'],['Information remains available only briefly unless it undergoes further ___.',['processing','depositing off','confinement','detention from'],'processing','cognitive processing collocation'],['Effective recall depends on meaningful cues and repeated ___.',['rehearsal','recollection of','reminder','reminiscence at'],'rehearsal','memory rehearsal collocation']
]);
addChoices('e4-','English in Use 4 - Precision verbs','English in Use','Academic English',[
 ['The self-important candidate ___ into the interview room as though he already had the post.',['strutted','slithered','crept','glided'],'strutted','movement verb implying proud display'],['The temperature gradually ___ towards forty degrees during the experiment.',['crept','strutted','slithered','glided'],'crept','movement verb for gradual numerical increase'],['The canoe ___ silently across the surface of the lake.',['glided','strutted','crept','slithered'],'glided','smooth effortless movement'],['A small snake ___ through a gap beneath the laboratory door.',['slithered','glided','strutted','marched'],'slithered','movement of a snake'],['The available funding has ___ considerably since last year.',['diminished','condensed','shrunk something','contracted an object'],'diminished','intransitive reduction in amount'],['The woollen laboratory coat ___ after being washed at the wrong temperature.',['shrank','diminished it','condensed itself','lessened it'],'shrank','physical reduction in size'],['The department must ___ expenditure without reducing student support.',['reduce','shrink itself','diminish by','contract down'],'reduce','transitive verb for making an amount smaller'],['The regional economy ___ during the prolonged transport strike.',['contracted','condensed it','reduced itself by','lessened something'],'contracted','intransitive economic decline'],['Please provide a ___ version of the report for the committee.',['condensed','diminished','contracted down','lessened'],'condensed','adjective meaning shortened'],['Repeated absences gradually ___ her chances of completing the course.',['lessened','contracted them by','condensed','shrunk herself'],'lessened','transitive reduction in degree']
]);

export const unit5Sections=[
 {track:'Grammar',count:unit5Questions.filter(item=>item.track==='Grammar').length,description:'Reported statements, questions, commands and advanced reporting-verb patterns.'},
 {track:'Vocabulary',count:unit5Questions.filter(item=>item.track==='Vocabulary').length,description:'Education & Learning vocabulary, phrasal verbs, collocations, idioms and transformations with Spanish support.'},
 {track:'English in Use',count:unit5Questions.filter(item=>item.track==='English in Use').length,description:'C2 word formation, transformations, cloze work and precision vocabulary.'}
];
