// C2 Booster - Unit 10: Nouns + Travel & Tourism. All prompts are original.
function tok(a,s){return a.replace(/[.?!]$/,'').split(/\s+/).map((w,i)=>({w,n:(i*71+s*53)%179})).sort((a,b)=>a.n-b.n).map(x=>x.w)}
function q(id,act,track,cat,source,choices,answer,rule,key='',glosses={}){return{id:'b10-'+id,exam:'BOOSTER',cefr:'C2',unit:'Unit 10',activity:act,track,category:cat,mode:key?'build':'choice',source,keyword:key,answer:answer.replace(/[.?!]$/,''),choices,tokens:tok(answer,Number(id.replace(/\D/g,''))||1),rule,glosses,explanation:`This item practises ${rule}.`,commonError:'Check countability, number, agreement, possessive form and the precise travel collocation.',miniLesson:'Nouns encode people, objects, groups, substances and concepts; their countability and form determine agreement, articles and quantity expressions.'}}
function C(p,a,t,c,x){x.forEach(([s,ch,ans,r],i)=>unit10Questions.push(q(p+String(i+1).padStart(2,'0'),a,t,c,s,ch,ans,r)))}function B(p,a,t,c,x){x.forEach(([s,k,ans,r],i)=>unit10Questions.push(q(p+String(i+1).padStart(2,'0'),a,t,c,s,[],ans,r,k)))}export const unit10Questions=[];

// GRAMMAR - 80.
C('g1-','Grammar 1 - Countable and uncountable nouns','Grammar','Nouns',[
 ['The consultant gave us some useful ___.',['advice','advices','an advice','advises noun'],'advice','uncountable advice'],['We need additional ___ before deciding.',['information','informations','an information','informative'],'information','uncountable information'],['The hotel provided every guest with clean ___.',['bedding','beddings','a bedding','bed clotheses'],'bedding','uncountable collective material'],['Her research has produced compelling ___.',['evidence','evidences','an evidence','evidentials'],'evidence','uncountable evidence'],['The laboratory purchased new ___.',['equipment','equipments','an equipment','equipping pieces'],'equipment','uncountable equipment'],['There is little ___ for oversized luggage.',['room','rooms space','a room space','roomes'],'room','uncountable room meaning space'],['The gallery contains several important ___.',['works of art','work of arts','works of arts','art workses'],'works of art','countable work meaning creation'],['Could we have two ___, please?',['coffees','coffee uncountable only','coffeeses','cup coffee'],'coffees','countable serving use'],['The region produces several excellent ___.',['wines','wine only uncountable','wineses','wine kindses'],'wines','countable varieties'],['She has extensive ___ of aviation law.',['knowledge','knowledges','a knowledge generally','knowledgees'],'knowledge','uncountable abstract noun'],['The investigators found three distinct ___ in the account.',['inconsistencies','inconsistency uncountable','inconsistencys','inconsistentnesses'],'inconsistencies','countable abstract instances'],['The renovation caused considerable ___.',['damage','damages generally','a damage','damaging noun plural'],'damage','uncountable damage'],['The court awarded substantial ___.',['damages','damage singular award','a damages','damagings'],'damages','legal plural damages'],['We had an unforgettable ___ during the expedition.',['experience','experiences uncountable here','experiencing','experiencement'],'experience','countable event'],['She has limited ___ in crisis management.',['experience','experiences generally','an experiences','experientiality'],'experience','uncountable expertise'],['There was too much ___ on the motorway.',['traffic','traffics','a traffic','vehicles traffic count'],'traffic','uncountable traffic']
]);
C('g2-','Grammar 2 - Plural forms','Grammar','Nouns',[
 ['The observatory launched two unmanned ___.',['spacecraft','spacecrafts','spacecraftes','spacecraft’s'],'spacecraft','zero plural'],['Several ___ were grazing near the road.',['deer','deers','deeres','deer’s'],'deer','zero plural animal'],['The museum displays ceremonial ___.',['knives','knifes','knifees','knifs'],'knives','f to ves plural'],['Both ___ were based on incomplete assumptions.',['hypotheses','hypothesis','hypothesises','hypothesiseses'],'hypotheses','Greek plural'],['The survey included three separate ___.',['analyses','analysis','analysises','analysies'],'analyses','Greek plural analysis'],['Rare ___ can survive in extreme environments.',['species','speciess','specie','specieses'],'species','unchanged plural'],['The children received educational ___.',['toys','toies','toyes','toy’s'],'toys','regular plural after vowel y'],['The archive contains medieval ___.',['manuscripts','manuscriptes','manuscript’s','manuscripta'],'manuscripts','regular plural'],['Several ___ attended the emergency meeting.',['chiefs','chieves','chiefes','chief’s'],'chiefs','exception to f-ves'],['The roofs of the mountain ___ were covered in snow.',['chalets','chalet’s','chaleties','chaletes'],'chalets','regular plural borrowed noun'],['The bacteria were visible under both ___.',['microscopes','microscopys','microscope’s','microscopia'],'microscopes','regular plural'],['The two ___ reached different conclusions.',['committees','committee’s','committeeses','committies'],'committees','vowel plus s'],['We observed unusual natural ___.',['phenomena','phenomenons','phenomenas','phenomenon’s'],'phenomena','Greek plural phenomenon'],['All relevant ___ were considered.',['criteria','criterions','criterias','criterion’s'],'criteria','Greek plural criterion'],['The mountain shelters several packs of ___.',['wolves','wolfs','wolfes','wolf’s'],'wolves','f to ves plural'],['The company acquired a fleet of electric ___.',['buses','busses only spelling error','bus’s','buseses'],'buses','sibilant plural']
]);
C('g3-','Grammar 3 - Agreement and collective nouns','Grammar','Nouns',[
 ['The committee ___ reached its final decision.',['has','have each members explicitly','are','were having'],'has','collective noun as a unit'],['The police ___ investigating the complaint.',['are','is','has','was'],'are','plural-only police'],['The news ___ far more encouraging today.',['is','are','were plural','have'],'is','singular uncountable news'],['Mathematics ___ compulsory in the first year.',['is','are','have','were plural'],'is','academic subject singular'],['The cattle ___ moved to higher ground.',['were','was','is','has'],'were','plural collective cattle'],['A series of delays ___ disrupted the project.',['has','have nearest noun','are','were'],'has','head noun series singular'],['The number of visitors ___ increased sharply.',['has','have','are','were'],'has','the number singular'],['A number of visitors ___ complained.',['have','has','is','was'],'have','a number of plural'],['The staff ___ divided in their opinions.',['are','is unit agreement only here','has','was'],'are','collective members acting separately'],['Ten kilometres ___ too far to walk in this heat.',['is','are','have','were'],'is','distance as singular unit'],['The outskirts of the city ___ poorly connected.',['are','is','has','was'],'are','plural-only outskirts'],['The contents of the suitcase ___ missing.',['are','is','has','was'],'are','plural contents'],['Economics ___ her strongest subject.',['is','are','have','were'],'is','subject ending s singular'],['The scissors ___ in the top drawer.',['are','is','has','was'],'are','plural pair noun'],['Each of the proposals ___ merit.',['has','have','are having','were having'],'has','each singular agreement'],['Neither of the explanations ___ convincing.',['is','are always','have','were'],'is','neither singular formal agreement']
]);
C('g4-','Grammar 4 - Possessives and noun phrases','Grammar','Nouns',[
 ['We discussed the ___ long-term strategy.',['company’s','companies','companys','company of'],'company’s','singular possessive'],['The ___ passports were checked together.',['travellers’','traveller’s plural','travellers','travelleres'],'travellers’','plural possessive'],['The decision was made at ___ notice.',['a moment’s','a moments','one moment of','moments’s'],'a moment’s','time possessive'],['The cottage is within ___ walk of the beach.',['ten minutes’','ten minute’s','ten minutes','ten-minutes’s'],'ten minutes’','plural time possessive'],['The ___ toys were packed separately.',['children’s','childrens’','childrens','children of'],'children’s','irregular plural possessive'],['The roof ___ requires repair.',['of the terminal','the terminal’s roof position formal only','of terminal’s','terminal of'],'of the terminal','of phrase with inanimate position'],['We admired the colour ___.',['of the sunset','the sunset’s colour always preferred','of sunset’s','sunset colour of'],'of the sunset','of phrase inanimate'],['This is a colleague of ___.',['Marta’s','Marta','Marta’ colleague','the Marta’s'],'Marta’s','double possessive'],['The delay was nobody ___.',['else’s fault','elses fault','else fault’s','else their fault'],'else’s fault','possessive with else'],['We stayed at my ___ house.',['parents’','parent’s plural','parents','parents’s'],'parents’','regular plural possessive'],['The article examines ___ impact.',['climate change’s','the impact of climate change','climate changes impact','the climate’s change impact'],'the impact of climate change','complex inanimate of phrase'],['The two hotels share a ___ entrance.',['common','commons','commonly noun','community'],'common','attributive noun phrase'],['The guide gave us a ___ explanation.',['twenty-minute','twenty-minutes','twenty minutes’ adjective','twenty minute’s'],'twenty-minute','compound noun modifier'],['We booked a ___ tour.',['three-day','three-days','three day’s','three days'],'three-day','number noun compound modifier'],['The airline announced several ___ measures.',['cost-cutting','costs-cutting','cost-cuttings','cutting-costs'],'cost-cutting','noun participle compound'],['The report considers ___ safety.',['passenger','passengers plural modifier','passenger’s general class','passengering'],'passenger','singular noun modifier']
]);
B('g5-','Grammar 5 - Noun transformations','Grammar','Nominalisation',[
 ['The committee decided to postpone the launch.','DECISION','The committee made the decision to postpone the launch','verb to noun collocation'],['People strongly opposed the new airport.','OPPOSITION','There was strong opposition to the new airport','nominalisation'],['The number of visitors increased dramatically.','INCREASE','There was a dramatic increase in visitor numbers','nominalisation with in'],['The guide described the route accurately.','DESCRIPTION','The guide gave an accurate description of the route','give a description'],['The airline failed to explain the cancellation.','EXPLANATION','The airline gave no explanation for the cancellation','explanation for'],['The company intends to expand overseas.','INTENTION','The company has the intention of expanding overseas','intention of gerund'],['They analysed the data thoroughly.','ANALYSIS','They carried out a thorough analysis of the data','carry out analysis'],['The city has developed rapidly.','DEVELOPMENT','The city has undergone rapid development','undergo development'],['The inspector recommended immediate closure.','RECOMMENDATION','The inspector made a recommendation for immediate closure','make recommendation'],['Residents complained repeatedly about noise.','COMPLAINTS','Residents made repeated complaints about noise','make complaints'],['The renovation improved accessibility considerably.','IMPROVEMENT','The renovation brought a considerable improvement in accessibility','improvement in'],['The two accounts differ significantly.','DIFFERENCE','There is a significant difference between the two accounts','difference between'],['Nobody objected to the proposed itinerary.','OBJECTION','There was no objection to the proposed itinerary','objection to'],['Passenger numbers declined slightly.','DECLINE','There was a slight decline in passenger numbers','decline in'],['The authorities permitted overnight camping.','PERMISSION','The authorities gave permission for overnight camping','permission for'],['She responded immediately to our request.','RESPONSE','She gave an immediate response to our request','give response']
]);

// VOCABULARY - 128.
function L(p,a,c,e){const g={journey:'viaje',route:'ruta',tour:'recorrido',trip:'viaje',...Object.fromEntries(e.map(x=>[x[0],x[1]]))},pool=[...new Set(e.map(x=>x[0]))];e.forEach(([ans,,s],i)=>{const al=pool.filter(x=>x!==ans),z=[];for(let k=0;k<al.length&&z.length<3;k++){const v=al[(i+k+1)%al.length];if(!z.includes(v))z.push(v)}while(z.length<3)z.push(['journey','route','tour','trip'].find(x=>x!==ans&&!z.includes(x)));unit10Questions.push(q(p+String(i+1).padStart(2,'0'),a,'Vocabulary',c,s,[ans,...z],ans,`precise ${c.toLowerCase()} usage`,'',g))})}
L('v1-','Vocabulary 1 - Air travel','Travel & Tourism',[
 ['carriage','vagón','Our seats were in the quiet ___.'],['customs','aduanas','All arriving passengers must pass through ___.'],['flight attendant','auxiliar de vuelo','A ___ demonstrated the safety procedure.'],['jet lag','desfase horario','It took several days to recover from ___.'],['oxygen mask','máscara de oxígeno','An ___ will drop automatically if required.'],['turbulence','turbulencia','Severe ___ forced everyone to remain seated.'],['transfer','traslado / conexión','The package includes airport ___.'],['stopover','escala','We had a six-hour ___ in Bogotá.'],['departure lounge','sala de embarque','Passengers waited in the ___.'],['boarding pass','tarjeta de embarque','Keep your ___ ready for inspection.'],['hand luggage','equipaje de mano','Liquids in ___ are restricted.'],['baggage allowance','franquicia de equipaje','Check your ___ before packing.'],['runway','pista de aterrizaje','The aircraft remained on the ___ awaiting clearance.'],['connecting flight','vuelo de conexión','A delay caused us to miss our ___.']
]);
L('v2-','Vocabulary 2 - Tourism essentials','Travel & Tourism',[
 ['high season','temporada alta','Prices rise considerably during ___.'],['low season','temporada baja','The resort is peaceful in ___.'],['hitchhiker','autoestopista','The driver picked up a lone ___.'],['hotspot','destino popular','The island has become a tourist ___.'],['island-hopping','recorrido entre islas','The itinerary includes a week of ___.'],['sunscreen','protector solar','Reapply ___ after swimming.'],['tourist trap','trampa para turistas','The overpriced restaurant was clearly a ___.'],['vacancy','habitación disponible','The sign outside announced a ___.'],['excursion','excursión','We booked a day ___ to the ruins.'],['itinerary','itinerario','The guide emailed the final ___.'],['resort','complejo turístico','The coastal ___ has three pools.'],['souvenir','recuerdo','She bought a handmade ___ from a local artisan.'],['hostel','hostal','Budget travellers often stay in a ___.'],['landmark','lugar emblemático','The cathedral is the city’s best-known ___.']
]);
L('v2b-','Vocabulary 2 - Travel documents','Travel & Tourism',[
 ['travel insurance','seguro de viaje','Comprehensive ___ is essential for an expedition of this kind.'],
 ['entry visa','visado de entrada','Visitors from some countries must obtain an ___ in advance.']
]);
L('v3-','Vocabulary 3 - Accommodation','Travel & Tourism',[
 ['suite','suite','They upgraded us to a sea-view ___.'],['fully furnished','completamente amueblado','We rented a ___ studio apartment.'],['room service','servicio a la habitación','Daily ___ is included in the rate.'],['single supplement','suplemento individual','Solo travellers must pay a ___.'],['all-inclusive','todo incluido','The ___ package covers meals and activities.'],['half board','media pensión','Our reservation includes ___.'],['self-catering','con cocina propia','The family preferred a ___ apartment.'],['vacation rental','alquiler vacacional','They booked a private ___ outside the centre.'],['amenities','servicios / comodidades','Hotel ___ include a gym and spa.'],['occupancy','ocupación','Room ___ reaches ninety per cent in July.'],['reception desk','mostrador de recepción','Leave your key at the ___.'],['late checkout','salida tardía','We requested a ___ for Sunday.'],['twin room','habitación doble con camas separadas','The colleagues shared a ___.'],['sea view','vista al mar','A balcony with a ___ costs extra.']
]);
L('v4-','Vocabulary 4 - Travel phrasal verbs','Phrasal Verbs',[
 ['fall through','fracasar / no realizarse','The expedition ___ when funding was withdrawn.'],['head off','partir','We plan to ___ before sunrise.'],['settle on','decidirse por','After comparing options, we ___ a small guesthouse.'],['go down with','enfermarse de','She ___ food poisoning abroad.'],['look up','mejorar','Bookings are beginning to ___.'],['clear up','despejarse','The weather should ___ by afternoon.'],['put up','alojar','Friends offered to ___ us ___ for the night.'],['narrow down','reducir opciones','We ___ the shortlist to three destinations.'],['put together','organizar / elaborar','The agency ___ a detailed itinerary.'],['see off','despedir','We went to the station to ___ them ___.'],['check in','registrarse','Guests can ___ from three o’clock.'],['set off','emprender viaje','We ___ on the final stage at dawn.'],['stop over','hacer escala','They ___ in Madrid for one night.'],['get away','escaparse de vacaciones','We hope to ___ for a long weekend.']
]);
L('v5-','Vocabulary 5 - Travel prepositions','Prepositions',[
 ['by','por','The driver was distracted ___ the commotion.'],['on','en','The tourists were stranded ___ the island.'],['for','por','After a month abroad, she longed ___ home cooking.'],['for','para','We agreed to stand by ___ a later flight.'],['of','de','Be wary ___ unofficial taxi drivers.'],['in','en','He dreams of a holiday ___ the mountains.'],['on','en','They spent the afternoon lazing ___ the beach.'],['because of','debido a','The excursion was cancelled ___ heavy rain.'],['from','de','The hotel is within walking distance ___ the centre.'],['at','en','We arrived ___ the terminal just before noon.']
]);
L('v6-','Vocabulary 6 - Travel collocations','Collocations',[
 ['travel light','viajar ligero','Experienced backpackers prefer to ___.'],['feel homesick','sentir nostalgia','Students abroad sometimes ___.'],['crystal-clear water','agua cristalina','The beach is famous for its ___.'],['city skyline','horizonte urbano','The rooftop offers views of the ___.'],['holiday wish list','lista de deseos de viaje','Patagonia is on my ___.'],['get stuck in traffic','quedarse atrapado en tráfico','Leave early or you may ___.'],['pay someone a visit','hacerle una visita a alguien','We decided to ___ while nearby.'],['safe journey','buen viaje','Everyone wished us a ___.'],['put on suncream','ponerse protector solar','Remember to ___ before hiking.'],['package holiday','paquete vacacional','A ___ may reduce planning time.'],['open-plan living room','sala de concepto abierto','The apartment has an ___.'],['stretches of sand','extensiones de arena','The coast has endless golden ___.'],['direct flight','vuelo directo','We found a ___ to Toronto.'],['guided tour','visita guiada','A ___ begins at the main gate.']
]);
L('v7-','Vocabulary 7 - Travel idioms','Idioms',[
 ['get a move on','darse prisa','We need to ___ or we will miss the train.'],['point taken','entiendo tu argumento','___; an overnight stop may be wiser.'],['off the beaten track','fuera de la ruta habitual','They prefer villages ___.'],['travel broadens the mind','viajar abre la mente','Many people believe that ___.'],['the world is your oyster','el mundo está a tus pies','With a remote job, ___.'],['itchy feet','ganas de viajar','After six months at home, she got ___.'],['live out of a suitcase','vivir de una maleta','Touring musicians often ___.'],['hit the road','ponerse en camino','We should ___ before traffic builds.'],['a stone’s throw','a un paso','The hostel is ___ from the station.'],['miss the boat','perder la oportunidad','Book now or you may ___.'],['go the extra mile','hacer un esfuerzo adicional','Excellent guides ___ for guests.'],['smooth sailing','marcha sin problemas','After customs, the journey was ___.'],['at a crossroads','en una encrucijada','The tourism industry is ___.'],['call it a day','dar por terminado','After eight hours of driving, we ___.'],['take the scenic route','tomar la ruta panorámica','We chose to ___.'],['on the go','muy activo / de un lado a otro','Tour leaders are constantly ___.']
]);
L('v8-','Vocabulary 8 - Travel expressions','Fixed Expressions',[
 ['deciding factor','factor decisivo','Price was the ___ when choosing the hotel.'],['open to debate','sujeto a debate','The benefits of mass tourism remain ___.'],['long haul','larga distancia','Compression socks help on ___ flights.'],['at short notice','con poca anticipación','The airline cancelled ___.'],['within easy reach','fácilmente accesible','Several beaches are ___.'],['home away from home','segundo hogar','The family-run inn felt like a ___.'],['peak travel period','periodo pico de viajes','Expect queues during the ___.'],['once-in-a-lifetime trip','viaje único en la vida','The safari was a ___.'],['local knowledge','conocimiento local','A guide offers valuable ___.'],['tourist season','temporada turística','Many businesses close outside the ___.'],['return fare','tarifa de ida y vuelta','The ___ is cheaper online.'],['travel arrangements','preparativos de viaje','The assistant finalised all ___.'],['change of scenery','cambio de ambiente','A weekend away provided a ___.'],['sense of adventure','espíritu aventurero','Solo travel requires a ___.']
]);
B('v9-','Vocabulary 9 - Travel transformations','Vocabulary','Vocabulary Transformations',[
 ['We must hurry or we will miss boarding.','MOVE','We must get a move on or we will miss boarding','get a move on'],['The apartment is very close to the cathedral.','THROW','The apartment is a stone’s throw from the cathedral','stone’s throw'],['The agent made an exceptional effort to help us.','MILE','The agent went the extra mile to help us','go extra mile'],['We chose the longer but more attractive road.','SCENIC','We chose to take the scenic route','scenic route'],['After months at home, she desperately wanted to travel.','FEET','After months at home she had itchy feet','itchy feet'],['The hostel felt as comfortable as our own house.','HOME','The hostel felt like a home away from home','home away from home'],['The weather improved shortly before departure.','CLEARED','The weather cleared up shortly before departure','clear up'],['Their holiday was cancelled when the operator collapsed.','FELL','Their holiday fell through when the operator collapsed','fall through'],['We reduced the options to two resorts.','NARROWED','We narrowed down the options to two resorts','narrow down'],['They began their journey before dawn.','SET','They set off before dawn','set off'],['We stayed with friends for one night.','PUT','Friends put us up for one night','put up'],['This might be your final opportunity to book.','BOAT','Book now or you may miss the boat','miss the boat'],['We ended the journey after reaching the border.','DAY','We called it a day after reaching the border','call it a day'],['The resort is easily accessible from the airport.','REACH','The resort is within easy reach of the airport','within easy reach'],['The guide’s knowledge of the area was invaluable.','LOCAL','The guide’s local knowledge was invaluable','local knowledge'],['Our journey proceeded without any further problems.','SAILING','The rest of our journey was smooth sailing','smooth sailing']
]);

// ENGLISH IN USE - 32.
C('e1-','English in Use 1 - Word formation','English in Use','Word Formation',[
 ['The island’s ___ landscape attracts hikers.',['mountainous','mountainly','mountained','mountainful'],'mountainous','adjective formation'],['Its dramatic coastline is almost ___.',['irresistible','unresisting','resistanceful','irresistedly'],'irresistible','negative adjective'],['The town has retained its architectural ___.',['distinctiveness','distinctly noun','distinctioned','distinctiveity'],'distinctiveness','abstract noun'],['Writers and ___ gathered there throughout the century.',['intellectuals','intellects people','intellectualnesses','intellectually noun'],'intellectuals','person noun'],['Tourism began to ___ after the 1960s.',['diminish','diminution verb','diminishingly','diminishedness'],'diminish','verb formation'],['Several villas remain privately ___.',['owned','ownership adjective','owningly','ownered'],'owned','past participle'],['The upper paths are largely ___.',['inaccessible','unaccessedful','accesslessness','inaccessibly adjective'],'inaccessible','negative adjective'],['The harbour is exceptionally ___.',['picturesque','picturedness','pictorially adjective','pictureful'],'picturesque','descriptive adjective']
]);
B('e2-','English in Use 2 - Transformations','English in Use','Advanced Structures',[
 ['Mr Vega must cancel tomorrow’s appointment.','CHOICE','Mr Vega has no choice but to cancel tomorrow’s appointment','have no choice but'],['She speaks Italian reasonably well.','COMMAND','She has a reasonable command of Italian','have command of'],['He gave Daniel money to purchase the ticket.','LOAN','He made Daniel a loan to purchase the ticket','make a loan'],['He speaks as though he knows the region intimately.','IMPRESSION','He gives the impression of knowing the region intimately','give impression'],['Sofia practises the violin almost daily.','GOES','Sofia rarely lets a day go by without practising the violin','let a day go by'],['He understood his affection only after she departed.','ABSENCE','Only her absence made him realise how much he cared','inversion with only'],['The fire completely destroyed the historic lodge.','NOTHING','The fire left nothing of the historic lodge','leave nothing of'],['The guide was so helpful that we tipped generously.','SUCH','He was such a helpful guide that we tipped generously','such noun that']
]);
C('e3-','English in Use 3 - Multiple-choice cloze','English in Use','Multiple-choice Cloze',[
 ['Bus travel is rarely considered a glamorous ___ of transport.',['mode','manner at','style of vehicle','fashion transport'],'mode','mode of transport'],['Some routes pass through magnificently ___ landscapes.',['scenic','scene-like at','scenery adjective','scenically noun'],'scenic','scenic landscape'],['Small buses ___ passengers between remote villages.',['ferry','transmit people technically','navigate passengers','haul unpleasantly'],'ferry','ferry passengers'],['One coastal route is considered a transport ___.',['masterpiece','perfection only','blockbuster film','masterstroke action only'],'masterpiece','metaphorical masterpiece'],['The service offers ___ views across the valley.',['glorious','proud','triumphant','gallant'],'glorious','glorious views'],['Drivers are unfailingly ___ to visitors.',['courteous','heroic','gallant battle','courtly historical'],'courteous','courteous to'],['The journey has become a tourist attraction in its own ___.',['right','law','justice','correctness'],'right','in its own right'],['Advance booking is strongly ___.',['recommended','commended only praise','proposed to person','advised of object'],'recommended','strongly recommended']
]);
C('e4-','English in Use 4 - Open cloze','English in Use','Open Cloze',[
 ['The island lies just ___ the mainland.',['off','out','from','away of'],'off','off the coast'],['It can be reached ___ ferry from the main port.',['by','with','on means','at'],'by','travel by ferry'],['The crossing takes little ___ an hour.',['over','above','more of','beyond than'],'over','little over'],['The harbour is very ___ crowded outside August.',['rarely','scarce','few','little'],'rarely','frequency adverb'],['Visitors can explore the island ___ foot.',['on','by','with','at'],'on','on foot'],['There is no need ___ hire a car.',['to','for hiring grammar','of','at'],'to','need to infinitive'],['The paths lead through villages, some of ___ have no road access.',['which','that','whom','where'],'which','some of which'],['The island is small enough to cross in a day ___ so.',['or','and','but','if'],'or','or so']
]);
export const unit10Sections=[{track:'Grammar',count:unit10Questions.filter(x=>x.track==='Grammar').length,description:'Countability, plurals, agreement, possessives, noun phrases and nominalisation.'},{track:'Vocabulary',count:unit10Questions.filter(x=>x.track==='Vocabulary').length,description:'Travel & Tourism vocabulary, phrasal verbs, collocations and idioms with Spanish support.'},{track:'English in Use',count:unit10Questions.filter(x=>x.track==='English in Use').length,description:'C2 word formation, transformations, multiple-choice cloze and open cloze.'}];
