// C2 Booster - Unit 13: Clauses + Sport & Leisure. All prompts are original.
function mix(text,seed){return text.replace(/[.?!]$/,'').split(/\s+/).map((word,index)=>({word,key:(index*79+seed*41)%193})).sort((a,b)=>a.key-b.key).map(item=>item.word)}
function q(id,activity,track,category,source,choices,answer,rule,keyword='',glosses={}){return{id:`b13-${id}`,exam:'BOOSTER',cefr:'C2',unit:'Unit 13',activity,track,category,mode:keyword?'build':'choice',source,keyword,answer:answer.replace(/[.?!]$/,''),choices,tokens:mix(answer,Number(id.replace(/\D/g,''))||1),rule,glosses,explanation:`This item practises ${rule}.`,commonError:'Check the logical relationship between clauses and the exact sporting collocation.',miniLesson:'Clauses express relationships such as contrast, time, reason, purpose, condition and result; conjunction choice determines that relationship.'}}
export const unit13Questions=[];
function C(prefix,activity,track,category,items){items.forEach(([source,choices,answer,rule],i)=>unit13Questions.push(q(`${prefix}${String(i+1).padStart(2,'0')}`,activity,track,category,source,choices,answer,rule)))}
function B(prefix,activity,track,category,items){items.forEach(([source,keyword,answer,rule],i)=>unit13Questions.push(q(`${prefix}${String(i+1).padStart(2,'0')}`,activity,track,category,source,[],answer,rule,keyword)))}

// GRAMMAR - 88.
C('g1-','Grammar 1 - Coordination and contrast','Grammar','Clauses',[
 ['The team trained intensively, ___ it still lost the final.',['yet','for','so that','since'],'yet','coordinating contrast'],['The course is ___ demanding ___ expensive.',['both / and','either / nor','neither / or','not only / but'],'both / and','correlative addition'],['The event was ___ well organised ___ remarkably inclusive.',['not only / but also','either / or','neither / nor','both / yet'],'not only / but also','emphatic addition'],['You may enter ___ the singles ___ the doubles competition.',['either / or','neither / and','both / nor','not only / or'],'either / or','correlative alternatives'],['___ the coach ___ the captain knew about the change.',['Neither / nor','Either / and','Both / or','Not only / nor'],'Neither / nor','negative addition'],['She cannot ski, ___ can she snowboard.',['nor','or','yet','for'],'nor','negative addition with inversion'],['The pitch was wet, ___ the match continued.',['but','because','so that','in order to'],'but','coordinating contrast'],['He apologised ___ refused to change his decision.',['but','so','for','or else purpose'],'but','contrast coordination'],['You can rest now, ___ you can finish the final lap first.',['or','nor','for','yet addition'],'or','alternative coordination'],['The gates opened early, ___ thousands of fans were already waiting.',['for','yet','or','nor'],'for','formal coordinating reason'],['The referee warned him, ___ he repeated the offence.',['yet','so that','because','for reason supporting first'],'yet','unexpected contrast'],['The club reduced fees ___ expanded its youth programme.',['and','but despite','or neither','for because'],'and','simple addition'],['She plays ___ chess ___ competitive bridge.',['both / and','either / nor','neither / or','not / but also missing'],'both / and','paired conjunction'],['It was not fatigue ___ a tactical error that cost them the match.',['but','and','or','for'],'but','not X but Y'],['The race was exhausting ___ immensely rewarding.',['but','because','unless','so as'],'but','adjective contrast'],['The spectators neither complained ___ left early.',['nor','or','and','but'],'nor','neither nor'],['The striker can play on the left ___ through the centre.',['or','nor','for','yet'],'or','alternative positions'],['She won the title, ___ she had been injured for months.',['although','because','so that','once'],'although','subordinating contrast']
]);
C('g2-','Grammar 2 - Contrast and comparison','Grammar','Advanced Structures',[
 ['___ the conditions were difficult, every runner finished.',['Although','Despite','Because of','In spite'],'Although','although plus clause'],['___ being significantly younger, she dominated the tournament.',['Despite','Although','Even though','Whereas'],'Despite','despite plus gerund'],['___ he practises daily, his brother trains only twice a week.',['Whereas','So that','Since reason only','Once'],'Whereas','contrast between clauses'],['The novice performed ___ confidently as the reigning champion.',['as','like','than','so that'],'as','as adjective as comparison'],['The routine is not as effortless ___ it appears.',['as','like','than','that'],'as','not as as'],['___ the favourite lost, the crowd remained supportive.',['Even though','Because','So that','Until'],'Even though','strong concession'],['___ happens, remain within the marked course.',['Whatever','However adjective needed','Whereas','Even if happens ungrammatical'],'Whatever','free relative concession'],['However ___ the climb becomes, do not abandon your partner.',['difficult','difficulty','difficultly','it difficult'],'difficult','however plus adjective'],['The first team attacked constantly, ___ the second defended deeply.',['while','so that','because','until'],'while','simultaneous contrast'],['The rule remains valid, ___ unpopular it may be.',['however','whatever noun','although of','whereas'],'however','however adjective clause'],['She competed ___ she had never been injured.',['as if','even though fact','because of','so as'],'as if','unreal comparison'],['The new stadium looks exactly ___ the architect intended.',['as','like clause informal','than','which'],'as','as plus clause'],['The match was closer ___ the score suggests.',['than','as','like','that'],'than','comparative clause'],['Strong ___ he is, he cannot lift that weight safely.',['though','despite','whereas','even'],'though','fronted concessive adjective'],['___ talented, no athlete succeeds without discipline.',['However','Whatever','Although of','As if'],'However','however adjective ellipsis'],['The strategy worked, ___ only temporarily.',['albeit','because','unless','therefore clause'],'albeit','formal concession'],['Much ___ I admire her, I disagree with that decision.',['as','like','although of','whereas'],'as','fronted concession'],['The team played well, ___ losing by two goals.',['despite','although','even though','whereas'],'despite','despite gerund']
]);
C('g3-','Grammar 3 - Time, place and condition','Grammar','Clauses',[
 ['The crowd erupted ___ the winning goal crossed the line.',['as soon as','until','while before','ever since'],'as soon as','immediate time'],['Wait here ___ the officials open the gate.',['until','since','whenever','after already completed'],'until','endpoint time'],['___ the whistle blows, the clock starts.',['Once','Although','Whereas','So that'],'Once','time condition'],['She has trained consistently ___ joining the academy.',['since','until','before','whenever'],'since','starting point'],['Warm up thoroughly ___ you begin the sprint session.',['before','after','while completed','since reason'],'before','prior time'],['___ you feel any sharp pain, stop immediately.',['Whenever','Whereas','Although','In order that'],'Whenever','repeated condition/time'],['We found a quiet field ___ the children could practise safely.',['where','when','which place without preposition','wherever any place'],'where','place clause'],['You may sit ___ you can see the scoreboard.',['wherever','whenever','whereas','however'],'wherever','unrestricted place'],['___ in doubt, ask the referee for clarification.',['When','Why','Where','Whether'],'When','reduced time/condition clause'],['___ necessary, the final will be postponed.',['If','Whether is','Although being','As though'],'If','reduced conditional clause'],['The players left ___ the press conference had finished.',['after','until before endpoint','whenever','since reason'],'after','sequence in time'],['___ the rain stopped, volunteers began drying the court.',['As soon as','Even if hypothetical','Whereas','So that'],'As soon as','immediate sequence'],['Stay behind the barrier ___ the race is in progress.',['while','since starting point','after','once completion'],'while','duration'],['No sooner had the bell rung ___ the runners set off.',['than','when','that','as'],'than','no sooner than'],['Hardly had we taken our seats ___ the lights went out.',['when','than','that','as soon'],'when','hardly when'],['The team will celebrate ___ the result is confirmed.',['once','unless contrast','whereas','even though fact'],'once','future time clause'],['Take a water break ___ you need one.',['whenever','however','whereas','whatever'],'whenever','repeated time'],['We will play ___ the weather remains safe.',['provided that','although','whereas','in spite of'],'provided that','conditional proviso']
]);
C('g4-','Grammar 4 - Reason, purpose and result','Grammar','Clauses',[
 ['The match was abandoned ___ lightning posed an immediate danger.',['because','so that','in order to','despite'],'because','reason clause'],['___ several players were injured, the squad was reshuffled.',['Since','So as to','Whereas','Even if'],'Since','reason given as known'],['The rule is useful ___ it prevents deliberate time-wasting.',['in that','so that purpose','although','wherever'],'in that','formal explanation'],['___ we have no floodlights, the game must finish before sunset.',['Seeing that','In order that','Even though contrary','Whereas contrast'],'Seeing that','reason based on circumstances'],['The organisers added signs ___ spectators could find their seats.',['so that','because','although','insofar as'],'so that','purpose clause'],['She lowered her voice so as not ___ the concentration of other players.',['to disturb','disturb','disturbing','disturbed'],'to disturb','negative purpose infinitive'],['The lanes were widened in order ___ wheelchair racers safely.',['to accommodate','that accommodate missing subject','accommodating','for accommodate'],'to accommodate','purpose infinitive'],['Training was adjusted ___ each athlete could recover properly.',['in order that','because of','despite','whereas'],'in order that','formal purpose clause'],['The wind was ___ strong that play became impossible.',['so','such','too much','enough'],'so','so adjective that'],['It was ___ a close contest that neither side relaxed.',['such','so','too','rather than'],'such','such noun phrase that'],['The more regularly you practise, ___ your reactions become.',['the faster','faster than','the fastest','as fast'],'the faster','correlative comparative'],['The instructions were written ___ as to prevent ambiguity.',['in such a way','so much a way','such way','in a way so that to'],'in such a way','in such a way as to'],['Now ___ the season is over, the stadium can be renovated.',['that','when that','which','as if'],'that','now that'],['The club introduced childcare, thereby ___ more parents to participate.',['enabling','to enable after thereby','enabled','enable'],'enabling','thereby gerund result'],['The pitch froze, with the result ___ the fixture was cancelled.',['that','which','of','as'],'that','with the result that'],['He trained at altitude ___ improve his endurance.',['so as to','because','although','in that'],'so as to','purpose infinitive'],['The evidence was inconclusive, ___ a second test was arranged.',['so','for','yet','nor'],'so','coordinating result'],['The injury was serious enough ___ him out of the tournament.',['to rule','ruling','that rule without subject','for rule'],'to rule','enough to result']
]);
B('g5-','Grammar 5 - Clause transformations','Grammar','Advanced Structures',[
 ['Although the team was inexperienced, it reached the final.','DESPITE','Despite being inexperienced the team reached the final','concession transformation'],['The organisers delayed the start to protect the runners.','ORDER','The organisers delayed the start in order to protect the runners','purpose'],['We left immediately after the whistle sounded.','SOON','We left as soon as the whistle sounded','time clause'],['The course became harder as we climbed higher.','HIGHER','The higher we climbed the harder the course became','double comparative'],['She continued competing although she was exhausted.','EVEN','She continued competing even though she was exhausted','strong concession'],['The gym introduced classes because members had requested them.','SEEING','The gym introduced classes seeing that members had requested them','reason'],['He does not play tennis and he does not play squash.','NEITHER','He plays neither tennis nor squash','negative coordination'],['The venue is modern and it is accessible.','ONLY','The venue is not only modern but also accessible','emphatic addition'],['You can train on Tuesday or on Thursday.','EITHER','You can train either on Tuesday or on Thursday','alternative'],['The weather may deteriorate, but the race will continue.','EVEN','The race will continue even if the weather deteriorates','conditional concession'],['The referee explained the rule so everyone could understand it.','ORDER','The referee explained the rule in order that everyone could understand it','purpose clause'],['I admire the athlete, but I cannot support her conduct.','MUCH','Much as I admire the athlete I cannot support her conduct','fronted concession'],['The exercise looks simple but is actually demanding.','AS','The exercise is not as simple as it looks','comparison'],['Once the gates open, spectators may enter.','UNTIL','Spectators may not enter until the gates open','time endpoint'],['Wherever the team plays, supporters follow.','MATTER','No matter where the team plays supporters follow','concession/place'],['The food was so good that everyone requested more.','SUCH','It was such good food that everyone requested more','such that']
]);

// VOCABULARY - 120.
function L(prefix,activity,category,entries){const glosses=Object.fromEntries(entries.map(([word,translation])=>[word,translation])),pool=entries.map(entry=>entry[0]);entries.forEach(([answer,,source],i)=>{const choices=[answer];for(let n=1;choices.length<4;n++){const candidate=pool[(i+n)%pool.length];if(!choices.includes(candidate))choices.push(candidate)}unit13Questions.push(q(`${prefix}${String(i+1).padStart(2,'0')}`,activity,'Vocabulary',category,source,choices,answer,`precise ${category.toLowerCase()} usage`,'',glosses))})}
L('v1-','Vocabulary 1 - Team sports','Sport & Leisure',[
 ['striker','delantero','The ___ converted both chances in the second half.'],['squad','plantilla / equipo','The coach announced a twenty-player ___.'],['assist','asistencia','Her precise pass provided the winning ___.'],['foul','falta','The referee awarded a free kick for the ___.'],['substitute','suplente','A late ___ scored with his first touch.'],['captain','capitán','The ___ spoke on behalf of the players.'],['defender','defensa','The central ___ blocked the shot.'],['goalkeeper','portero','The ___ saved the decisive penalty.'],['fixture','partido programado','Saturday’s league ___ has been postponed.'],['draw','empate','A late equaliser secured a ___.'],['league','liga','The club currently leads the national ___.'],['tournament','torneo','Thirty-two teams entered the international ___.']
]);
L('v2-','Vocabulary 2 - Competition','Sport & Leisure',[
 ['title','título','She retained the world ___ convincingly.'],['triumph','triunfo','Completing the expedition was a personal ___.'],['runner-up','subcampeón','Last year’s ___ returned to the final.'],['knockout stage','fase eliminatoria','Only sixteen teams reach the ___.'],['qualifier','partido clasificatorio','The final ___ takes place in Lima.'],['championship','campeonato','He withdrew from the continental ___.'],['record','récord','The swimmer broke the national ___.'],['podium','podio','Both athletes finished on the ___.'],['medal','medalla','She won a bronze ___ in cycling.'],['opponent','oponente','His next ___ is known for powerful serves.'],['victory','victoria','The home crowd celebrated a narrow ___.'],['defeat','derrota','The coach accepted responsibility for the ___.']
]);
L('v3-','Vocabulary 3 - Individual sports','Sport & Leisure',[
 ['stroke','estilo / brazada','Butterfly is the most demanding swimming ___.'],['club','palo de golf','Choose a shorter ___ for this shot.'],['lap','vuelta','She took the lead on the final ___.'],['lane','carril','The fastest qualifier was assigned the centre ___.'],['serve','saque','His powerful ___ produced another ace.'],['rally','intercambio de golpes','The longest ___ lasted forty shots.'],['sprint','carrera corta','The final ___ decided the cycling race.'],['marathon','maratón','Training for a ___ requires gradual progression.'],['paddle','remo corto','Each kayaker carried a spare ___.'],['harness','arnés','Inspect your climbing ___ before ascending.'],['helmet','casco','A certified ___ is compulsory.'],['racket','raqueta','The player changed her ___ between sets.']
]);
L('v4-','Vocabulary 4 - Games and hobbies','Sport & Leisure',[
 ['dice','dados','Roll both ___ to begin your turn.'],['counter','ficha','Move your ___ three spaces forward.'],['pack','baraja / mazo','The dealer opened a new ___ of cards.'],['shuffle','barajar','Give the cards a thorough ___.'],['riddle','acertijo','The final ___ required lateral thinking.'],['puppet show','espectáculo de títeres','The children watched an interactive ___.'],['platform game','juego de plataformas','The retro ___ rewards precise timing.'],['role-playing game','juego de rol','Players create characters in the ___.'],['skipping rope','cuerda para saltar','A ___ provides an inexpensive cardio workout.'],['board game','juego de mesa','The strategy ___ takes about ninety minutes.'],['jigsaw puzzle','rompecabezas','They completed a thousand-piece ___.'],['pottery','cerámica','Evening ___ classes help her relax.']
]);
L('v5-','Vocabulary 5 - Training and participation','Sport & Leisure',[
 ['strenuous','extenuante','Avoid ___ exercise immediately after illness.'],['recreational','recreativo','The centre offers ___ activities for all ages.'],['withdraw','retirarse','The injured player had to ___ from the event.'],['dismiss','expulsar','The referee may ___ a player for violent conduct.'],['intercept','interceptar','The defender managed to ___ the pass.'],['qualify','clasificar','Only the top two teams will ___.'],['warm up','calentar','Athletes should ___ before intense exercise.'],['cool down','enfriar gradualmente','Walk slowly to ___ after running.'],['endurance','resistencia física','Long-distance swimming builds ___.'],['stamina','aguante','The second half tested their ___.'],['agility','agilidad','The drill develops speed and ___.'],['coordination','coordinación','Ball games improve hand-eye ___.']
]);
L('v6-','Vocabulary 6 - Sport phrasal verbs','Phrasal Verbs',[
 ['catch up on','ponerse al día con','The holiday gave me time to ___ some sleep.'],['cheer on','animar','Thousands gathered to ___ the cyclists.'],['cry out for','necesitar urgentemente','The neighbourhood is ___ a public sports centre.'],['figure out','descifrar / comprender','It took us several attempts to ___ the rules.'],['get into','aficionarse a','She recently ___ indoor climbing.'],['get round to','finalmente hacer','I finally ___ repairing my bicycle.'],['hold off','posponer','Officials decided to ___ the match until evening.'],['hold on','resistir / esperar','The exhausted leader managed to ___ until the finish.'],['keep at','persistir','If you ___ the routine, your balance will improve.'],['kick off','comenzar','The final will ___ at eight.'],['move on','seguir adelante / marcharse','After ten seasons, the veteran decided to ___.'],['pick up','recibir','The midfielder ___ a yellow card.']
]);
L('v7-','Vocabulary 7 - Sport collocations','Collocations',[
 ['do aerobics','hacer aeróbicos','She goes to the gym to ___ twice a week.'],['do archery','practicar tiro con arco','Visitors can ___ under supervision.'],['play badminton','jugar bádminton','We ___ in the community hall.'],['go climbing','hacer escalada','They ___ in the Andes each summer.'],['go cycling','salir en bicicleta','We often ___ along the coastal road.'],['play chess','jugar ajedrez','He learned to ___ at five.'],['go fishing','ir de pesca','They ___ before sunrise.'],['play golf','jugar golf','Executives sometimes ___ after the conference.'],['go hiking','hacer senderismo','Take sufficient water when you ___.'],['do judo','practicar judo','The children ___ at a local club.'],['go sailing','navegar a vela','We ___ whenever the wind is suitable.'],['do weightlifting','hacer levantamiento de pesas','Athletes ___ with qualified coaches.']
]);
L('v8-','Vocabulary 8 - Sport idioms','Idioms',[
 ['gain ground','ganar terreno','Women’s football continues to ___.'],['go great guns','ir estupendamente','The new youth programme is ___.'],['on top of the world','sentirse en la cima','After breaking the record, she felt ___.'],['when push comes to shove','a la hora de la verdad','___, discipline matters more than talent.'],['the last straw','la gota que colmó el vaso','Another cancelled session was ___.'],['call it a day','dar por terminado','After fifteen seasons, he decided to ___.'],['make someone’s day','alegrarle el día a alguien','Meeting her sporting hero ___ her ___.'],['see red','ponerse furioso','The captain ___ after the reckless tackle.'],['on fire','en racha / imparable','The striker is ___ this season.'],['put money on','apostar por','I would ___ Brazil reaching the final.'],['lose sight of','perder de vista','Coaches must not ___ enjoyment.'],['let off steam','liberar tensión','Exercise helps office workers ___.']
]);
L('v9-','Vocabulary 9 - Leisure expressions','Fixed Expressions',[
 ['come under fire','recibir fuertes críticas','The organisers ___ over ticket prices.'],['fall to pieces','venirse abajo','The team ___ after conceding twice.'],['hold your own','defenderse bien','The teenager managed to ___ against experienced players.'],['better safe than sorry','más vale prevenir que lamentar','Pack an extra layer: ___.'],['put someone on the spot','poner a alguien en aprietos','The interviewer ___ the coach ___.'],['keep someone posted','mantener informado','Please ___ me ___ about the fixture.'],['green with envy','muerto de envidia','Their rivals were ___ after the victory.'],['excel yourself','superarse','She ___ and achieved a personal best.'],['in attendance','presente / asistiendo','More than thirty thousand fans were ___.'],['in luck','tener suerte','We were ___ when two tickets became available.'],['on loan','cedido temporalmente','The young goalkeeper is ___ for a season.'],['margin of error','margen de error','Electronic timing has a tiny ___.']
]);
B('v10-','Vocabulary 10 - Sport transformations','Vocabulary','Vocabulary Transformations',[
 ['The community urgently needs a swimming pool.','CRYING','The community is crying out for a swimming pool','cry out for'],['Supporters encouraged the team loudly.','CHEERED','Supporters cheered on the team loudly','cheer on'],['She persisted with the training programme.','KEPT','She kept at the training programme','keep at'],['Officials postponed the start because of lightning.','HELD','Officials held off the start because of lightning','hold off'],['The striker is performing exceptionally well.','FIRE','The striker is on fire','on fire'],['The defeat caused the team to collapse emotionally.','PIECES','The team fell to pieces after the defeat','fall to pieces'],['Exercise allows me to release tension.','STEAM','Exercise allows me to let off steam','let off steam'],['The organisers were strongly criticised.','FIRE','The organisers came under fire','come under fire'],['The novice competed successfully against experts.','OWN','The novice held her own against experts','hold your own'],['The victory made him extremely happy.','WORLD','The victory made him feel on top of the world','on top of world'],['Another injury was the final unacceptable problem.','STRAW','Another injury was the last straw','last straw'],['The veteran decided to retire.','DAY','The veteran decided to call it a day','call it a day']
]);

// ENGLISH IN USE - 32.
C('e1-','English in Use 1 - Word formation','English in Use','Word Formation',[
 ['The athlete achieved an ___ level of consistency.',['unprecedented','precedeless incorrect','unprecedingly','precedential different meaning'],'unprecedented','negative adjective'],['The programme offers ___ activities for younger children.',['imaginative','imaginarily','imagination adjective error','imaging'],'imaginative','adjective formation'],['His excessive ___ irritated the officials.',['impoliteness','unpolite noun','impolitely noun','politeness opposite'],'impoliteness','negative abstract noun'],['She felt increasingly ___ before the selection race.',['uneasy','diseased','easelessly','unease adjective error'],'uneasy','negative adjective'],['The player asked the referee for ___.',['forgiveness','forgivingness less idiomatic','forgive noun error','forgiven'],'forgiveness','abstract noun'],['A ___ training schedule undermines progress.',['disorganised','unorganisation adjective','disorganisingly','organised opposite'],'disorganised','negative participial adjective'],['Volunteers are important ___ to community sport.',['contributors','contributions people error','contributaries','contributing noun plural error'],'contributors','person noun'],['It remains ___ whether the plan is affordable.',['questionable','questioningly','questionedness','unquestioned opposite'],'questionable','adjective formation']
]);
B('e2-','English in Use 2 - Transformations','English in Use','Advanced Structures',[
 ['Please reply as soon as possible.','GRATEFUL','I would be grateful if you would reply as soon as possible','polite request'],['Nobody knows why the player resigned.','CAUSED','Nobody knows what caused the player to resign','causative question'],['This performance is slightly better than the previous one.','MARGINALLY','This performance is marginally better than the previous one','degree adverb'],['She cried uncontrollably after losing the final.','FLOODS','She was in floods of tears after losing the final','fixed expression'],['The coach stressed the importance of discipline.','EMPHASIS','The coach placed emphasis on the importance of discipline','nominalisation'],['We immediately realised that his excuse was false.','THROUGH','We immediately saw through his excuse','phrasal verb'],['The centre offers a considerable variety of classes.','ARRAY','The centre offers a wide array of classes','fixed collocation'],['He is naturally talented at ball games.','FLAIR','He has a natural flair for ball games','have a flair for']
]);
C('e3-','English in Use 3 - Multiple-choice cloze','English in Use','Multiple-choice Cloze',[
 ['The underwater goals have a ___ of about forty centimetres.',['diameter','equator','margin measuring uncertainty','circumference full boundary length'],'diameter','circle measurement'],['Each team has six players and six ___.',['substitutes','surrogates legal representatives','stand-ins informal actors','backups data copies'],'substitutes','sport replacement player'],['___ an opponent is permitted only while they hold the ball.',['Tackling','Eluding','Defying','Confronting verbally'],'Tackling','sport action'],['Contact is allowed ___ long as possession continues.',['as','for','like','such'],'as','as long as'],['The ___-filled ball is slightly negatively buoyant.',['saltwater','deep-sea adjective location','nautical related navigation','marine general adjective'],'saltwater','compound material adjective'],['The ball may ___ passed in any direction.',['be','been','have','being'],'be','modal passive'],['Water ___ rapidly stops the ball.',['resistance','opposition deliberate','contention dispute','hostility emotion'],'resistance','physical resistance'],['Good positioning and team ___ are essential.',['tactics','gimmicks','proceedings','manipulations deceptive acts'],'tactics','team tactics']
]);
C('e4-','English in Use 4 - Open cloze','English in Use','Open Cloze',[
 ['Most of ___ picture familiar childhood board games.',['us','we subject','our possessive','ours'],'us','most of pronoun'],['___ there is one strategy game that remains universal.',['Yet','So purpose','For reason preceding unsupported','Nor negative'],'Yet','contrast connector'],['Children can use ___ to develop concentration.',['it','itself reflexive unnecessary','them plural','its possessive'],'it','pronoun reference'],['Many begin learning as early ___ age five.',['as','than','like','at'],'as','as early as'],['Parents can assess readiness ___ observing reactions to losing.',['by','with means less exact before gerund','through of','at'],'by','by gerund method'],['Players must learn to take ___ and accept defeat.',['turns','times','orders','chances randomness'],'turns','take turns'],['Ensure the child is interested ___ the activity remains enjoyable.',['so that','because of','despite','whereas'],'so that','purpose/result clause'],['Once readiness is clear, it is time to get ___.',['started','starting transitive missing object','start','to started'],'started','get started']
]);

export const unit13Sections=[
 {track:'Grammar',count:unit13Questions.filter(item=>item.track==='Grammar').length,description:'Coordination, contrast, time, place, reason, purpose, preference and result clauses.'},
 {track:'Vocabulary',count:unit13Questions.filter(item=>item.track==='Vocabulary').length,description:'Sport & Leisure vocabulary, phrasal verbs, collocations and idioms with Spanish support.'},
 {track:'English in Use',count:unit13Questions.filter(item=>item.track==='English in Use').length,description:'C2 word formation, transformations, multiple-choice cloze and open cloze.'}
];
