// C2 Booster - Unit 04
// Original C2 practice based only on the unit skill map: Passive Voice,
// Relationships & People, and English in Use.

function tokens(answer,seed){return answer.replace(/[.?!]$/,'').split(/\s+/).map((word,i)=>({word,n:(i*43+seed*29)%131})).sort((a,b)=>a.n-b.n).map(x=>x.word)}
function q(id,activity,track,category,source,choices,answer,rule,keyword='',glosses={}){const mode=keyword?'build':'choice';return{id:'b4-'+id,exam:'BOOSTER',cefr:'C2',unit:'Unit 04',activity,track,category,mode,source,keyword,answer:answer.replace(/[.?!]$/,''),choices,tokens:tokens(answer,Number(id.replace(/\D/g,''))||1),rule,glosses,explanation:`This item practises ${rule}.`,commonError:'Check the tense, object focus, dependent preposition and whether the agent is necessary.',miniLesson:'The passive shifts attention from the agent to the action, recipient, result or process.'}}
function addChoices(prefix,activity,track,category,items){items.forEach(([source,choices,answer,rule],i)=>unit4Questions.push(q(prefix+String(i+1).padStart(2,'0'),activity,track,category,source,choices,answer,rule)))}
function addBuilds(prefix,activity,track,category,items){items.forEach(([source,keyword,answer,rule],i)=>unit4Questions.push(q(prefix+String(i+1).padStart(2,'0'),activity,track,category,source,[],answer,rule,keyword)))}
export const unit4Questions=[];

// GRAMMAR - 109 items.
addChoices('g1-','Grammar 1 - Passive forms','Grammar','Passive Voice',[
 ['The artisan ice cream ___ locally sourced fruit and fresh cream.',['is made with','makes with','is making from','has made by'],'is made with','present simple passive plus with for ingredients'],
 ['Two unmarked vehicles ___ outside the warehouse before dawn.',['were seen arriving','were arrived','saw to arrive','had seen arriving'],'were seen arriving','passive perception verb plus -ing for an action in progress'],
 ['According to witnesses, the cyclist ___ by debris from the collapsing wall.',['was struck','struck','has striking','was been struck'],'was struck','past simple passive'],
 ['During the interview, I ___ several questions about my previous research.',['was asked','asked me','have asking','was being ask'],'was asked','passive with a person as subject'],
 ['The suspect ___ crossing the border shortly before midnight.',['was seen','saw to be','has seen','was seeing'],'was seen','passive of a perception verb'],
 ['This side entrance ___ only for emergency evacuation.',['is used','uses','is using','has use'],'is used','present simple passive for function'],
 ['Personal devices cannot ___ inside the secure laboratory.',['be used','to be used','being used','have using'],'be used','modal plus passive infinitive'],
 ['Open-source tools ___ by an increasing number of public institutions.',['are being adopted','have adopting','are adopted currently by','adopt'],'are being adopted','present continuous passive for an ongoing trend'],
 ['I hope your application ___ more favourably after the additional evidence.',['is viewed','views','is viewing','has view'],'is viewed','present simple passive after hope'],
 ['The vegetables ___ slowly in a sealed clay oven.',['were cooked','cooked themselves','had cooking','were being cook'],'were cooked','past simple passive'],
 ['The minister ___ by two senior civil servants during the negotiations.',['was assisted','assisted with','was assisting','had assist'],'was assisted','past simple passive with an agent'],
 ['The proposal ___ by several members of the governing coalition.',['is being challenged','is challenging','has challenge','was been challenged'],'is being challenged','present continuous passive'],
 ['The encryption system ___ to prevent unauthorised access.',['is relied on','relies on it','is being rely','has relied by'],'is relied on','passive of a verb with dependent preposition'],
 ['The first municipal railway ___ in the region in 1898.',['was constructed','constructed itself','has constructed','was constructing'],'was constructed','past simple passive for a historical event'],
 ['The consultant ___ to say that the timetable was unrealistic.',['was heard','heard him','was hearing','has been hear'],'was heard','passive reporting with perception verb'],
 ['The instructions must be phrased so that they ___ by non-specialists.',['can be understood','can understand','are understanding','have understood'],'can be understood','modal passive'],
 ['By 2035, substantial areas of wetland ___ unless stronger protection is introduced.',['will have been lost','will have lost','are losing','have been losing'],'will have been lost','future perfect passive'],
 ['The testimonials on the website claim ___ by verified customers.',['to have been written','to have written','being written','to be writing'],'to have been written','perfect passive infinitive'],
 ['Standard parcels ___ from Monday to Saturday.',['are delivered','deliver themselves','have delivering','are being deliver'],'are delivered','present simple passive for routine'],
 ['Children ___ clear boundaries as part of their social development.',['are taught','teach them','are teaching','have teach'],'are taught','passive with recipient as subject'],
 ['The bridge ___ in the early 1970s and now requires extensive repairs.',['was established','has establishing','is established then','established itself'],'was established','past simple passive with a finished time'],
 ['The final candidate should ___ over the applicant who lacks relevant experience.',['be chosen','have choosing','choose','be choosing'],'be chosen','modal passive infinitive'],
 ['The province ___ apart by years of internal conflict.',['was torn','has tearing','tore itself by','was being tear'],'was torn','idiomatic past passive'],
 ['Every encrypted backup ___ in a separate physical location.',['must be stored','must store','is to storing','has been store'],'must be stored','obligation expressed with modal passive']
]);

addChoices('g2-','Grammar 2 - Active or passive','Grammar','Passive Voice',[
 ['Looking back, I could ___ by the dismissive remark, but I chose to ignore it.',['have been offended','have offended','be offending','have been offending'],'have been offended','modal perfect passive'],
 ['Global temperature readings ___ continuously by thousands of monitoring stations.',['are recorded','have recording','record themselves','are being record'],'are recorded','present simple passive for a routine process'],
 ['A great deal can ___ from carefully comparing the two accounts.',['be learned','learn','be learning','have learned'],'be learned','modal passive'],
 ['Investigators reported that the aircraft might ___ by an unauthorised drone.',['have been approached','have approached','be approaching','have been approaching'],'have been approached','modal perfect passive'],
 ['The guest rooms ___ every morning throughout our stay.',['were cleaned','were cleaning','have cleaned themselves','cleaned them'],'were cleaned','past simple passive'],
 ['The reporter ___ from official briefings after publishing confidential material.',['was excluded','excluded herself','has excluding','was being exclude'],'was excluded','past simple passive'],
 ['For this independent review, I ___ temporary access to the premium version.',['was given','was gave','gave me','have giving'],'was given','passive with indirect object as subject'],
 ['There is growing speculation that the club could ___ before the season ends.',['be sold','have sold','be selling','sell itself by'],'be sold','modal passive infinitive'],
 ['Provided the children ___ and cared for, the arrangement should work well.',['are respected','respect','are respecting','have respect'],'are respected','coordinated present passive'],
 ['Several patients ___ that the service may be withdrawn next year.',['have been told','have told','are telling','were being tell'],'have been told','present perfect passive'],
 ['Most of the emergency funding ___ to regions already carrying substantial debt.',['was lent','has lending','lent itself','was being lend'],'was lent','past simple passive with two objects'],
 ['Cardholders ___ that replacement cards would arrive within five working days.',['were informed','informed them','were informing','had inform'],'were informed','past simple passive reporting'],
 ['The community energy programme ___ next year to include smaller municipalities.',['will be expanded','will expand it','will be expanding by','has expanded tomorrow'],'will be expanded','future simple passive']
]);

addBuilds('g3-','Grammar 3 - Passive transformations','Grammar','Passive Voice',[
 ['Someone removed the confidential file from her desk.','TAKEN','The confidential file was taken from her desk','past simple passive'],
 ['The committee will examine the ethical issue in due course.','CONSIDERATION','The ethical issue will be given consideration in due course','give consideration passive'],
 ['The guards forced her to leave the restricted area.','MADE','She was made to leave the restricted area','passive of make plus full infinitive'],
 ['My grandparents permitted me to stay up late during holidays.','ALLOWED','I was allowed to stay up late during holidays','let changes to be allowed in passive'],
 ['The organisers will send invitations to every shortlisted candidate.','INVITE','Every shortlisted candidate will be invited by the organisers','future passive with recipient subject'],
 ['Witnesses saw him enter the abandoned building.','SEEN','He was seen to enter the abandoned building','passive perception plus full infinitive'],
 ['She silenced her phone because she did not want anyone to interrupt her.','AVOID','She silenced her phone to avoid being interrupted','avoid plus passive -ing form'],
 ['We will approve the scheme after receiving a detailed budget.','APPROVAL','The scheme will be given approval after we receive a detailed budget','passive collocation give approval'],
 ['The contract requires you to pay the instalment every month.','PAID','The instalment must be paid every month under the contract','modal passive obligation'],
 ['I dislike unfamiliar people asking me about my private life.','BEING','I dislike being asked about my private life by unfamiliar people','passive -ing form'],
 ['The regulations prohibit calculators in this assessment.','ALLOWED','Calculators are not allowed to be used in this assessment','passive permission structure'],
 ['People claim that two teenagers wrote the bestselling novel.','SAID','The bestselling novel is said to have been written by two teenagers','reporting passive plus perfect infinitive'],
 ['The patient could not walk, so staff transported him in a wheelchair.','CARRIED','The patient had to be carried in a wheelchair','passive after have to'],
 ['You must keep all emergency exits clear.','KEPT','All emergency exits must be kept clear','modal passive'],
 ['Do not allow their comments to intimidate you.','YOURSELF','Do not let yourself be intimidated by their comments','reflexive passive after let'],
 ['Someone has used all the printer ink.','BEEN','All the printer ink has been used','present perfect passive'],
 ['A sudden sense of relief overwhelmed her.','STRUCK','She was struck by a sudden sense of relief','be struck by an emotion']
]);

// A 31-step sustainable glass-production process, alternating active and passive choices.
addChoices('g4-','Grammar 4 - Passive in processes','Grammar','Passive Voice',[
 ['Most recycled glass ___ from household collection points.',['is obtained','obtains','is obtaining','has obtain'],'is obtained','present simple passive in a process'],
 ['Additional containers ___ each week to maintain a steady supply.',['are collected','collect','are collecting themselves','have collect'],'are collected','present simple passive'],
 ['At the sorting centre, unsuitable materials ___ by trained staff.',['are removed','remove','are removing','have removed them'],'are removed','present simple passive'],
 ['The rejected material ___ to specialist waste facilities.',['is then sent','then sends','is sending then','has then send'],'is then sent','sequenced present passive'],
 ['Acceptable bottles ___ according to colour.',['are separated','separate them','are separating','have separate'],'are separated','present simple passive'],
 ['A conveyor belt ___ the containers towards the crushing unit.',['carries','is carried by','has carrying','carry'],'carries','active present for process machinery'],
 ['Each batch ___ for ceramic fragments and heat-resistant glass.',['is inspected','inspects','is inspecting','has inspect'],'is inspected','present simple passive'],
 ['Any remaining labels ___ with jets of high-pressure water.',['are loosened','loosen themselves by','are loosening','have loosen'],'are loosened','present simple passive'],
 ['The cleaned containers ___ into small pieces known as cullet.',['are crushed','crush','are crushing','have crushing'],'are crushed','present simple passive'],
 ['Powerful magnets ___ metal caps from the moving cullet.',['extract','are extracted','have extracting','extracts'],'extract','active verb with machinery as agent'],
 ['Fine particles ___ through vibrating screens.',['are filtered','filter themselves','are filtering','have filter'],'are filtered','present simple passive'],
 ['The cullet can then ___ with carefully measured raw materials.',['be combined','combine itself','be combining','have combined'],'be combined','modal passive'],
 ['Silica sand and limestone ___ to improve consistency.',['are added','add themselves','are adding','have add'],'are added','present simple passive'],
 ['The mixture ___ in a furnace at extremely high temperatures.',['is heated','heats itself','is heating','has heat'],'is heated','present simple passive'],
 ['Modern furnaces ___ heat from the outgoing gases.',['recover','are recovered','have recovering','recovers'],'recover','active process verb'],
 ['By this stage, the solid ingredients ___ into molten glass.',['have been transformed','have transformed themselves by','are transforming yesterday','had transform'],'have been transformed','present perfect passive for achieved process result'],
 ['The molten material ___ continuously to remove trapped air.',['is stirred','stirs itself','is stirring','has stir'],'is stirred','present simple passive'],
 ['Sensors ___ the temperature throughout the operation.',['monitor','are monitored by the temperature','have monitoring','monitors'],'monitor','active present with instrument subject'],
 ['When the correct consistency ___, the glass moves to the forming area.',['has been reached','has reached it','is reaching','was reach'],'has been reached','present perfect passive in a time clause'],
 ['Measured portions ___ into heat-resistant moulds.',['are poured','pour themselves','are pouring','have pour'],'are poured','present simple passive'],
 ['Compressed air ___ each portion against the mould walls.',['presses','is pressed by each portion','has pressing','press'],'presses','active process verb'],
 ['The newly formed containers ___ gradually to prevent cracking.',['are cooled','cool them','are cooling by workers','have cool'],'are cooled','present simple passive'],
 ['Their temperature ___ in a computer-controlled chamber.',['is reduced','reduces itself by','is reducing','has reduce'],'is reduced','present simple passive'],
 ['Every bottle ___ for structural weakness.',['is tested','tests','is testing itself','has test'],'is tested','present simple passive'],
 ['High-speed cameras ___ tiny flaws invisible to the human eye.',['detect','are detected','have detecting','detects'],'detect','active process verb'],
 ['Defective containers ___ back into the recycling stream.',['are returned','return them','are returning by','have return'],'are returned','present simple passive'],
 ['Approved bottles ___ with production codes.',['are marked','mark themselves','are marking','have mark'],'are marked','present simple passive'],
 ['The finished products ___ in reusable protective crates.',['are packed','pack themselves','are packing','have pack'],'are packed','present simple passive'],
 ['Each shipment ___ before leaving the factory.',['is documented','documents itself','is documenting','has document'],'is documented','present simple passive'],
 ['Electric vehicles ___ many of the crates to regional distributors.',['transport','are transported by crates','have transporting','transports'],'transport','active present with vehicle subject'],
 ['The containers can eventually ___ and recycled again.',['be collected','collect themselves','be collecting','have collected'],'be collected','modal passive in a cyclical process']
]);

addChoices('g5-','Grammar 5 - Advanced passive challenge','Grammar','Passive Voice',[
 ['In the dystopian novel, every public statement ___ by a central authority.',['is controlled','controls itself','is controlling','has control'],'is controlled','present simple passive'],
 ['This revised edition is based on the version that ___ in 2019.',['was published','published it','was publishing','has publish'],'was published','past simple passive'],
 ['The finalist ___ from the competition after breaching the rules.',['was eliminated','eliminated himself by','was eliminating','has eliminate'],'was eliminated','past simple passive'],
 ['I am afraid this is not the first time he ___ behaving irresponsibly.',['has been found','has found','is finding','was been found'],'has been found','present perfect passive plus -ing complement'],
 ['A suitable location ___ and construction will begin shortly.',['has been selected','has selected itself','is selecting','was selection'],'has been selected','present perfect passive'],
 ['I ___ for explaining publicly why the experiment had failed.',['was criticised','criticised me','have criticising','was being criticise'],'was criticised','past simple passive plus dependent preposition'],
 ['Yesterday I ___ whether the inquiry would be reopened.',['was asked','asked to me','was asking by','have ask'],'was asked','past simple passive with a person subject'],
 ['The missed penalty ___ within seconds when the opposing team scored.',['was forgotten','forgot itself','was forgetting','has forget'],'was forgotten','past simple passive'],
 ['The coastal land ___ by the municipality in 1984.',['was acquired','acquired itself','has acquired in 1984','was acquiring'],'was acquired','past simple passive with definite date'],
 ['When our luggage ___ by the airline, we were offered compensation.',['was misplaced','misplaced itself','has misplacing','was being misplace'],'was misplaced','past simple passive'],
 ['The sports hall ___ to the original school building in the 1960s.',['was added','added itself','has added in the 1960s','was adding'],'was added','past simple passive'],
 ['This online guidance ___ up to date by a specialist editorial team.',['is kept','keeps itself','is keeping','has keep'],'is kept','present simple passive state'],
 ['How can I ensure that my research proposal ___?',['will be approved','will approve itself','is approving','has approval'],'will be approved','future passive'],
 ['The live broadcast was taken off air after it ___ by an evacuation alarm.',['was interrupted','interrupted itself','is being interrupted','has interrupt'],'was interrupted','past simple passive'],
 ['Use a thermometer to ensure that the poultry ___ thoroughly.',['has been cooked','has cooked itself','is cooking by','had cook'],'has been cooked','present perfect passive for completed result'],
 ['The final decision ___ after all consultation responses have been analysed.',['will be made','will make itself','is making','will have make'],'will be made','future simple passive'],
 ['Thousands of olive trees ___ in the recent wildfires.',['have been destroyed','have destroyed themselves','are destroying','have been destroying'],'have been destroyed','present perfect passive'],
 ['The scientist ___ as a guest on several documentary programmes.',['has appeared','has been appeared','is being appeared','was appeared'],'has appeared','intransitive verb requiring active voice'],
 ['One of the vehicles ___ by customs officers at the border.',['was searched','searched itself','was searching','has search'],'was searched','past simple passive'],
 ['More than eight thousand residents ___ by the renewable-energy sector.',['are employed','employ themselves by','are employing','have employ'],'are employed','present simple passive'],
 ['The battle against the epidemic ___ by medical teams across the region.',['is being fought','is fighting','has fight','was been fought'],'is being fought','present continuous passive'],
 ['The anthem ___ to the melody of a traditional coastal song.',['is sung','sings itself','is singing by','has sing'],'is sung','present simple passive'],
 ['The policy ___ by commercial interests rather than scientific evidence.',['is being driven','is driving','has drove','was been driven'],'is being driven','present continuous passive idiom'],
 ['During the interview, I ___ whether any research posts were vacant.',['was asked','asked me','was asking','have been ask'],'was asked','past simple passive']
]);

// VOCABULARY - Relationships & People, 117 items.
function lexical(prefix,activity,category,entries){const glosses=Object.fromEntries(entries.map(([w,es])=>[w,es]));const pool=[...new Set(entries.map(([w])=>w))];entries.forEach(([answer,,source],i)=>{const alternatives=pool.filter(w=>w!==answer);const choices=[answer,...[1,3,5].map(step=>alternatives[(i+step)%alternatives.length])];unit4Questions.push(q(prefix+String(i+1).padStart(2,'0'),activity,'Vocabulary',category,source,choices,answer,`precise ${category.toLowerCase()} usage`,'',glosses))})}
lexical('v1-','Vocabulary 1 - Relationship nouns','Relationships & People',[
 ['attraction','atracción','Their friendship gradually developed into a relationship based on mutual ___.'],['hospitality','hospitalidad','The family’s extraordinary ___ made every visitor feel at home.'],['inheritance','herencia','The dispute concerns the division of a substantial family ___.'],['affair','aventura amorosa / asunto','She discovered that her partner had been having an ___.'],['break-up','ruptura','Following the painful ___, they agreed not to contact each other.'],['settlement','acuerdo / convenio','The former couple finally reached a financial ___.'],['heritage','herencia cultural / patrimonio','He is proud of his mixed Peruvian and Italian ___.'],['custody','custodia','The parents agreed to share ___ of their two children.']
]);
lexical('v2-','Vocabulary 2 - Family members','Relationships & People',[
 ['sibling','hermano o hermana','Her younger ___ has always been her closest confidant.'],['heir','heredero','The will identifies his eldest daughter as the principal ___.'],['descendant','descendiente','She is a direct ___ of one of the town’s founders.'],['ex','expareja','My ___ and I remain on friendly terms for our children’s sake.'],['spouse','cónyuge','Employees may include their ___ in the health plan.'],['extended family','familia extensa','The celebration brought together cousins and other members of the ___.'],['orphan','huérfano','The charity provides long-term support for every ___ in its care.']
]);
lexical('v3-','Vocabulary 3 - Relationship verbs','Relationships & People',[
 ['foster','acoger temporalmente / fomentar','The couple decided to ___ two children while their mother recovered.'],['dissolve','disolver','They jointly petitioned the court to ___ the marriage.'],['flirt','coquetear','He attempted to ___ with her, but she changed the subject.'],['dump','dejar bruscamente a una pareja','Ending a serious relationship by text is a cruel way to ___ someone.'],['part','separarse','After twelve years together, the musicians decided to ___ amicably.'],['bond','crear un vínculo','Shared routines help new parents ___ with their babies.'],['befriend','hacerse amigo de','A neighbour chose to ___ the isolated elderly man.'],['disown','repudiar / desheredar','Her relatives threatened to ___ her if she rejected the arranged marriage.']
]);
lexical('v4-','Vocabulary 4 - Relationship adjectives','Relationships & People',[
 ['compatible','compatible','Although they disagree politically, they are remarkably ___.'],['intimate','íntimo / cercano','The memoir reveals ___ details about the author’s marriage.'],['hospitable','hospitalario','Our hosts were warm and exceptionally ___.'],['distant','distante','After the argument, he became emotionally ___.'],['elder','mayor de dos hermanos','As the ___ brother, he assumed responsibility for the household.'],['devoted','entregado / fiel','She remained a ___ friend throughout his illness.'],['platonic','platónico','Their relationship has always been close but entirely ___.']
]);
lexical('v5-','Vocabulary 5 - Relationship phrasal verbs','Phrasal Verbs',[
 ['relate to','identificarse con / comprender','Good counsellors can ___ people from very different backgrounds.'],['come between','interponerse entre','They promised that professional rivalry would never ___ them.'],['associate with','relacionarse con','Parents worried about the people their son had begun to ___.'],['fit in','encajar','At first she struggled to ___ with her partner’s large family.'],['fall for','enamorarse de / caer en un engaño','He did not expect to ___ someone he had met online.'],['break down','fracasar / deteriorarse','Their communication began to ___ under financial pressure.'],['make up','reconciliarse','After a week of silence, the sisters finally ___.'],['get out of','evitar / librarse de','He invented an excuse to ___ attending the reunion.'],['hold out for','esperar hasta conseguir','She decided to ___ a relationship based on genuine respect.'],['get round','persuadir / convencer','The children knew exactly how to ___ their strict grandfather.'],['keep back','ocultar','She suspected that her friend was trying to ___ important information.'],['fall out','pelearse / dejar de ser amigos','The two colleagues ___ over a misunderstanding.'],['put aside','dejar de lado','For their daughter’s sake, they agreed to ___ their differences.'],['run down','menospreciar / criticar','Constantly trying to ___ your partner damages trust.']
]);
lexical('v6-','Vocabulary 6 - Relationship prepositions','Prepositions',[
 ['with','con','She pleaded ___ him to reconsider the separation.'],['on','en','He insisted ___ leaving before the discussion had finished.'],['with','con','Some people become unhealthily obsessed ___ a new partner.'],['for','por','The parents were increasingly anxious ___ their missing daughter.'],['with','con','New students were encouraged to mix ___ people outside their course.'],['about','por / acerca de','She felt uneasy ___ leaving the child with an unfamiliar babysitter.'],['with','con','Daily contact helps parents bond ___ a newborn.'],['with','con','Being compatible ___ somebody does not mean sharing every opinion.'],['to','para / con','The rural community was extremely hospitable ___ newcomers.'],['by','por','He was disowned ___ relatives who opposed the marriage.']
]);
lexical('v7-','Vocabulary 7 - Relationship collocations','Collocations',[
 ['close-knit','muy unida','She grew up in a ___ family where everyone supported one another.'],['warm','cálida','The exchange student received a ___ welcome from her host family.'],['dysfunctional','disfuncional','The drama portrays a wealthy but deeply ___ family.'],['affair','aventura amorosa','The politician admitted having an ___ with a colleague.'],['acrimonious','hostil / encarnizado','Their ___ divorce attracted unwanted media attention.'],['childhood','de la infancia','Two of her closest ___ friends attended the ceremony.'],['intimate','íntima / cercana','They developed an ___ relationship based on mutual trust.'],['partner','pareja','He confessed that he had cheated on his ___.']
]);
lexical('v8-','Vocabulary 8 - Relationship idioms','Idioms',[
 ['take her for granted','darla por sentada','Do not ___; appreciation matters in a long relationship.'],['break the ice','romper el hielo','A light-hearted question helped ___ at the family dinner.'],['put my foot down','ponerme firme','I eventually had to ___ and refuse further interference.'],['give and take','tolerancia y concesiones mutuas','Every lasting partnership requires some ___.'],['plenty more fish in the sea','hay muchas más opciones','After the breakup, her friends reminded her that there were ___.'],['nearest and dearest','seres más queridos','He celebrated the promotion with his ___.'],['head over heels','perdidamente enamorado','Within weeks, they were ___ in love.'],['part company','separarse / tomar caminos distintos','The business partners agreed to ___ after the dispute.'],['pour oil on troubled waters','calmar una situación tensa','Their aunt tried to ___ during the family argument.'],['under his breath','entre dientes','He muttered an apology ___.'],['bang their heads together','obligarlos a entrar en razón','Someone needed to ___ before the disagreement escalated.'],['tie the knot','casarse','After a decade together, they finally decided to ___.'],['stick her nose into','entrometerse en','She has a habit of trying to ___ other people’s private affairs.'],['cramp my style','limitar mi libertad / estilo','Sharing a tiny flat with relatives would seriously ___.'],['get on like a house on fire','llevarse de maravilla','The two new colleagues immediately ___.'],['hit it off','conectar de inmediato','They ___ at the conference and remained close friends.'],['keep an eye on','vigilar / cuidar','Could you ___ the children while I answer the door?'],['make a go of it','intentar que funcione','Despite the distance, they are determined to ___.'],['a shoulder to cry on','alguien en quien apoyarse','After the separation, she needed ___.'],['keep a straight face','mantener la seriedad','I could not ___ when he described the disastrous date.']
]);
lexical('v9-','Vocabulary 9 - Relationship fixed expressions','Fixed Expressions',[
 ['in a flash','en un instante','They recognised each other ___ despite the years apart.'],['for good','para siempre','After repeated arguments, he left the household ___.'],['worn out','agotado','Caring for three young children left both parents ___.'],['take it for granted','darlo por sentado','Never ___ that relatives will always agree with you.'],['take issue with','objetar / discrepar con','She chose to ___ his dismissive attitude.'],['give me your word','darme tu palabra','Before I tell you, please ___ that you will keep it private.'],['make it public','hacerlo público','The couple waited several months before deciding to ___.'],['spring to mind','venir a la mente','Which quality first ___ when you think of a loyal friend?'],['march off','marcharse enfadado','Rather than discuss the problem, he would ___ to his room.'],['make allowances for','ser comprensivo con','We must ___ the pressure she is currently under.'],['speak your mind','decir lo que realmente piensas','You can disagree respectfully and still ___.'],['in confidence','en confianza / en secreto','She told me about the engagement ___.'],['where you stand','saber cuál es tu situación','An honest conversation will help you understand ___.'],['a sure thing','algo seguro','Their reconciliation is far from ___.'],['not think much of','tener mala opinión de','My parents did ___ my former partner.'],['tell the difference','notar la diferencia','The twins are so alike that strangers cannot ___.']
]);

addBuilds('v10-','Vocabulary 10 - Relationship transformations','Vocabulary','Vocabulary Transformations',[
 ['He rarely shows enthusiasm for collaborative projects.','GENERATE','He seems unable to generate enthusiasm for collaborative projects','generate enthusiasm'],['Almost nobody was present at the centre in August.','VIRTUALLY','The centre was virtually empty in August','virtually empty'],['The argument increased her resentment.','RESULTED','The argument resulted in increased resentment','result in'],['The directors held a private meeting about the policy.','DOORS','The directors met behind closed doors to discuss the policy','behind closed doors'],['She will almost certainly arrive before May ends.','LIKELIHOOD','In all likelihood she will arrive before the end of May','in all likelihood'],['Young children frequently ask many questions.','APT','Young children are apt to ask many questions','be apt to'],['I would rather stay awake than burden you.','IMPOSE','I do not want to impose on you','impose on'],['The manager is investigating the complaint.','LOOKED','The complaint is being looked into by the manager','look into passive'],['She often exaggerates the amount she earns.','TENDENCY','She has a tendency to exaggerate how much she earns','have a tendency to'],['Anne has decided to purchase fewer clothes.','CUT','Anne has decided to cut down on buying clothes','cut down on'],['May often ignores advice from her parents.','NOTICE','May rarely takes any notice of her parents’ advice','take notice of'],['I was about to answer when he phoned.','POINT','I was on the point of answering when he phoned','on the point of plus -ing'],['Her mother smiled broadly when she received the flowers.','LIT','Her mother’s face lit up when she received the flowers','face lights up'],['His rude outburst was inconsistent with his personality.','KEEPING','His rude outburst was out of keeping with his personality','out of keeping with'],['Nothing would persuade him to cheat in an examination.','CIRCUMSTANCES','Under no circumstances would he cheat in an examination','negative inversion'],['Since retiring, he devotes most of his time to gardening.','SPENT','Since retiring he has spent most of his time gardening','spend time plus -ing'],['The constant noise irritates Marie enormously.','FOREVER','Marie is forever losing patience because of the constant noise','be forever plus -ing'],['The board will not meet again before year-end.','HELD','No further board meeting will be held until the end of the year','future passive'],['Management has reached an agreement with the union.','STRUCK','Management has struck a deal with the union','strike a deal']
]);

// ENGLISH IN USE - 38 items.
const wf=[['disqualified','The director was ___ from holding office for six years.','QUALIFY'],['managerial','Applicants need at least three years of ___ experience.','MANAGER'],['obligatory','Two modules are ___ for every student on the programme.','OBLIGE'],['invalid','The document becomes ___ once its security code expires.','VALID'],['brightness','Adjust the ___ before editing the image contrast.','BRIGHT'],['embodies','Her conduct ___ the organisation’s commitment to inclusion.','BODY'],['justification','There is no legal ___ for withholding the evidence.','JUSTIFY'],['inadequate','The existing safeguards are plainly ___.','ADEQUATE'],['countless','There are ___ ways to support vulnerable relatives.','COUNT'],['curiosity','Out of ___, why did you contact your former colleague?','CURIOUS'],['atmospheric','The candlelit venue was intensely ___.','ATMOSPHERE'],['recognition','The qualification has gained international ___.','RECOGNISE'],['starvation','Emergency supplies protected the community from ___.','STARVE'],['definitive','It is impossible to give a ___ answer without further evidence.','DEFINE'],['openness','Honesty and ___ are essential to rebuilding trust.','OPEN']];
wf.forEach(([answer,source,base],i)=>unit4Questions.push(q('e1-'+String(i+1).padStart(2,'0'),'English in Use 1 - Word formation','English in Use','Word Formation',`${source} (${base})`,[answer,base.toLowerCase(),answer+'ly','un'+answer],answer,'word formation from the supplied base')));
addBuilds('e2-','English in Use 2 - Key word transformations','English in Use','Key Word Transformations',[
 ['I was furious with myself for missing the final train.','KICK','I wanted to kick myself for missing the final train','kick oneself'],['Some people accept that difficulties are unavoidable.','RESIGNED','Some people are resigned to difficulties being unavoidable','be resigned to'],['His errors occur too often for promotion to be possible.','FREQUENT','His errors are too frequent for him to be promoted','too plus adjective'],['Nothing will discourage her from visiting Brazil.','DETER','Nothing will deter her from visiting Brazil','deter from plus -ing'],['Nell frequently fails to honour her promises.','GOES','Nell often goes back on her promises','go back on a promise'],['Honesty has little influence in a corrupt administration.','COUNTS','Honesty counts for little in a corrupt administration','count for little'],['People regard Margaret as an excellent cook.','REPUTATION','Margaret has a reputation for being an excellent cook','have a reputation for']
]);
addChoices('e3-','English in Use 3 - Multiple-choice cloze','English in Use','Multiple-choice Cloze',[
 ['Chronic procrastinators identify ___ as unable to begin demanding tasks.',['themselves','them','their own','each other'],'themselves','reflexive pronoun'],['The behaviour affects every ___ of a person’s life.',['domain','boundary','territory','division'],'domain','precise abstract noun'],['Many organisations fail to ___ procrastination seriously.',['take','hold','weigh','think'],'take','take something seriously'],['Physical health is ___ area that may be affected.',['one','some','that','those'],'one','substitution with one'],['Delay imposes a considerable ___ on colleagues.',['cost','value','amount','expense of'],'cost','impose a cost on'],['Persistent delay ___ trust within a team.',['destroys','crushes physically','wipes','shatters into'],'destroys','verb collocation with trust'],['Anxiety increases as the deadline ___ closer.',['draws','pulls','arrives itself','reaches it'],'draws','draw closer'],['In ___, procrastination is a form of self-sabotage.',['short','reduction','epilogue','little'],'short','in short discourse marker']
]);
addChoices('e4-','English in Use 4 - Open cloze','English in Use','Open Cloze',[
 ['The precise origin of the name remains a point ___ contention.',['of','for','with','at'],'of','point of contention'],['One explanation is likely to derive ___ an ancient regional term.',['from','of','with','by'],'from','derive from'],['Another theory considers the modern name ___ a corruption of an older expression.',['to be','being','as being to','that be'],'to be','consider plus object plus infinitive'],['Several captives died ___ being transported across the mountains.',['while','during they','through','as to'],'while','while plus -ing clause'],['Evidence for this interpretation comes ___ a related verb in modern Persian.',['from','of','with','at'],'from','come from'],['It should ___ noted that the word once had a broader meaning.',['be','being','have','to be'],'be','passive after should'],['The original label applied irrespective ___ religious affiliation.',['of','from','to','with'],'of','irrespective of'],['The range may mark the final barrier travellers ___ to cross before reaching the plains.',['had','would having','were','have been'],'had','past perfect in historical sequence']
]);

export const unit4Sections=[
 {track:'Grammar',count:109,description:'Passive tenses, modals, perception and reporting verbs, two-object constructions, dependent prepositions and process descriptions.'},
 {track:'Vocabulary',count:117,description:'Relationships & People: family language, bonds, phrasal verbs, prepositions, collocations, idioms and transformations.'},
 {track:'English in Use',count:38,description:'Word formation, key word transformations, multiple-choice cloze and open cloze at C2 level.'}
];
if(unit4Questions.length!==264)throw new Error(`Unit 04 expected 264 items, got ${unit4Questions.length}`);
