// C2 Booster - Unit 09: Relative Clauses + Food & Drink.
// Original C2 practice based solely on the unit's linguistic skill map.
function tok(a,s){return a.replace(/[.?!]$/,'').split(/\s+/).map((w,i)=>({w,n:(i*67+s*47)%173})).sort((a,b)=>a.n-b.n).map(x=>x.w)}
function q(id,act,track,cat,source,choices,answer,rule,key='',glosses={}){return{id:'b9-'+id,exam:'BOOSTER',cefr:'C2',unit:'Unit 09',activity:act,track,category:cat,mode:key?'build':'choice',source,keyword:key,answer:answer.replace(/[.?!]$/,''),choices,tokens:tok(answer,Number(id.replace(/\D/g,''))||1),rule,glosses,explanation:`This item practises ${rule}.`,commonError:'Check whether the clause is defining, which element the pronoun replaces, and whether it can be omitted or reduced.',miniLesson:'Relative clauses identify, describe and connect information; advanced forms also express quantity, possession, place and formal prepositional relationships.'}}
function C(p,a,t,c,x){x.forEach(([s,ch,ans,r],i)=>unit9Questions.push(q(p+String(i+1).padStart(2,'0'),a,t,c,s,ch,ans,r)))}function B(p,a,t,c,x){x.forEach(([s,k,ans,r],i)=>unit9Questions.push(q(p+String(i+1).padStart(2,'0'),a,t,c,s,[],ans,r,k)))}
export const unit9Questions=[];

// GRAMMAR - 80.
C('g1-','Grammar 1 - Relative pronouns','Grammar','Relative Clauses',[
 ['The researcher ___ developed the model will present the findings.',['who','which','whose','where'],'who','who as subject for a person'],['The device, ___ was manufactured locally, has won an award.',['which','that','who','where'],'which','non-defining which'],['The candidate ___ portfolio impressed the panel was appointed.',['whose','who','whom','which'],'whose','possessive relative whose'],['This is the laboratory ___ the vaccine was developed.',['where','which','who','whose'],'where','relative adverb of place'],['The reason ___ the trial was suspended remains unclear.',['why','where','who','whose'],'why','relative adverb of reason'],['The consultant to ___ I spoke recommended further tests.',['whom','who','which','whose'],'whom','formal preposition plus whom'],['The report ___ you requested is attached.',['which','who','where','whose'],'which','object relative pronoun'],['Anyone ___ requires assistance should contact reception.',['who','which','whom object only','where'],'who','indefinite person antecedent'],['The year ___ the company was founded was unusually difficult.',['when','where','which place','whose'],'when','relative adverb of time'],['The policy, the consequences of ___ were severe, was withdrawn.',['which','that','whom','where'],'which','preposition plus which'],['The chef ___ restaurant received the award trained in Lima.',['whose','who','whom','which'],'whose','whose with a thing possessed'],['The ingredients from ___ the sauce is made are organic.',['which','whom','where','that after preposition'],'which','preposition plus which'],['She is one of the few critics ___ opinions I trust.',['whose','who','whom','which'],'whose','possessive relative'],['The village in ___ they stayed produces excellent cheese.',['which','where after in','whom','whose'],'which','formal preposition plus which'],['We met the nutritionist ___ had advised the national team.',['who','whom as subject','which','whose advice object'],'who','subject relative'],['The meal ___ we ordered never arrived.',['that','who','where','whose'],'that','defining object relative'],['The dining room, ___ overlooks the harbour, seats sixty.',['which','that','where','who'],'which','non-defining relative'],['That is the bakery ___ sourdough first became popular locally.',['where','which','whose','whom'],'where','place relative'],['The diners, several of ___ had allergies, requested separate menus.',['whom','who','which','whose'],'whom','quantifier plus whom'],['The recipes, most of ___ are centuries old, remain secret.',['which','that','whom','where'],'which','quantifier plus which']
]);
C('g2-','Grammar 2 - Defining and non-defining clauses','Grammar','Relative Clauses',[
 ['My aunt, ___ lives in Cusco, owns a small café.',['who','that','which','whom object'],'who','non-defining person clause'],['Employees ___ handle food must complete safety training.',['who','which','whose','where'],'who','defining subject clause'],['The original menu, ___ we found in the archive, was handwritten.',['which','that in non-defining','where','whose'],'which','non-defining object clause'],['Customers ___ bookings are confirmed receive a message.',['whose','who','whom','which'],'whose','defining possessive clause'],['The market ___ sells imported spices closes at six.',['that','where as subject','whose','whom'],'that','defining subject that'],['Our head chef, ___ you met yesterday, trained in France.',['whom','that','which','where'],'whom','non-defining object person'],['The only dish ___ contains nuts is clearly labelled.',['that','who','where','whose'],'that','that after only'],['Everything ___ was prepared this morning has been sold.',['that','who','where','whose'],'that','that after everything'],['The restaurant has two kitchens, neither of ___ is open to visitors.',['which','that','whom','where'],'which','neither of which'],['The suppliers, all of ___ are certified, undergo annual checks.',['whom','who','which','whose'],'whom','all of whom'],['The café ___ opened last month has already expanded.',['which','where subject','whose','whom'],'which','defining subject which'],['Pisco, ___ is distilled from grapes, is produced in Peru.',['which','that','where','who'],'which','non-defining fact'],['The person ___ we appointed will oversee quality control.',['whom','which','where','whose'],'whom','formal object relative'],['The last course ___ we tried was the most inventive.',['that','who','where','whose'],'that','that after superlative/ordinal context'],['There are several factors ___ influence flavour.',['that','where','whom','whose'],'that','defining subject clause']
]);
C('g3-','Grammar 3 - Advanced relative structures','Grammar','Advanced Structures',[
 ['The company employs sixty people, half of ___ work remotely.',['whom','who','which','whose'],'whom','quantity plus whom'],['The tasting produced five samples, none of ___ met the standard.',['which','that','whom','where'],'which','none of which'],['The chef explained the method, ___ surprised everyone.',['which','that','what','where'],'which','sentential which'],['They changed the recipe, as ___ expected.',['was','which was','that was','it was who'],'was','as was expected'],['The conference was postponed, at ___ point we left.',['which','that','what','whose'],'which','at which point'],['The food was served cold, ___ made matters worse.',['which','that','what','where'],'which','comment clause with which'],['We visited three farms, the largest of ___ supplies the hotel.',['which','that','whom','whose'],'which','superlative of which'],['The director rejected the proposal, ___ I considered unreasonable.',['which','that','what','where'],'which','object complement in non-defining clause'],['The manner in ___ the complaint was handled was exemplary.',['which','that','where','whom'],'which','in which formal manner'],['The extent to ___ prices have risen is alarming.',['which','that','where','what'],'which','to which extent'],['She introduced two sommeliers, both of ___ spoke Spanish.',['whom','who','which','whose'],'whom','both of whom'],['The week during ___ the festival takes place is extremely busy.',['which','when after during','that','whose'],'which','during which'],['The organisation for ___ she works promotes sustainable farming.',['which','whom','where','whose'],'which','preposition plus which organisation'],['The chef with ___ we collaborated published the recipe.',['whom','who','which','whose'],'whom','preposition plus whom'],['He missed the reservation, the reason for ___ was never explained.',['which','that','what','where'],'which','reason for which']
]);
B('g4-','Grammar 4 - Relative transformations','Grammar','Relative Clauses',[
 ['The woman owns the bakery. She won the regional award.','WHO','The woman who owns the bakery won the regional award','defining subject relative'],['The hotel has reopened. Its kitchen was completely renovated.','WHOSE','The hotel whose kitchen was completely renovated has reopened','possessive relative'],['We visited the district. The food festival began there.','WHERE','We visited the district where the food festival began','place relative'],['The inspection occurred on Monday. The restaurant was closed then.','WHEN','Monday was when the restaurant was closed for inspection','time relative'],['The waiter recommended the soup. I had spoken to him earlier.','WHOM','The waiter to whom I had spoken earlier recommended the soup','preposition plus whom'],['The sauce contains six spices. Three of them are imported.','WHICH','The sauce contains six spices three of which are imported','quantity plus which'],['The chef resigned unexpectedly. This shocked the entire team.','WHICH','The chef resigned unexpectedly which shocked the entire team','sentential which'],['The customers had allergies. All of them received separate meals.','WHOM','The customers all of whom had allergies received separate meals','all of whom'],['The reason is unknown. They cancelled the booking for that reason.','WHY','The reason why they cancelled the booking is unknown','reason why'],['This is the oven. The bread is baked in it.','WHICH','This is the oven in which the bread is baked','preposition plus which'],['The menu was redesigned by Ana. You met her yesterday.','WHOM','The menu was redesigned by Ana whom you met yesterday','object whom'],['The farm supplies our vegetables. It uses no pesticides.','THAT','The farm that supplies our vegetables uses no pesticides','defining that'],['They served an unfamiliar fruit. Its skin was bright purple.','WHOSE','They served an unfamiliar fruit whose skin was bright purple','whose for things'],['We attended the final tasting. The winner was announced there.','WHERE','We attended the final tasting where the winner was announced','where relative'],['The critic praised the service. That was unexpected.','WHICH','The critic praised the service which was unexpected','sentential which']
]);
B('g5-','Grammar 5 - Reduced relative clauses','Grammar','Relative Clauses',[
 ['Guests who arrive after ten must use the side entrance.','ARRIVING','Guests arriving after ten must use the side entrance','present participle reduction'],['The vegetables that were grown locally tasted exceptional.','GROWN','The vegetables grown locally tasted exceptional','past participle reduction'],['Anyone who wishes to complain should contact the manager.','WISHING','Anyone wishing to complain should contact the manager','active reduced relative'],['The meals that are included in the package are listed below.','INCLUDED','The meals included in the package are listed below','passive reduced relative'],['The first chef who completed the task received a prize.','TO','The first chef to complete the task received a prize','infinitive relative reduction'],['Customers who wait outside will receive a text message.','WAITING','Customers waiting outside will receive a text message','present participle reduction'],['The bottles that were stored incorrectly had spoiled.','STORED','The bottles stored incorrectly had spoiled','past participle reduction'],['The only applicant who understood the process was hired.','TO','The only applicant to understand the process was hired','infinitive after only'],['Dishes that contain raw egg are specially marked.','CONTAINING','Dishes containing raw egg are specially marked','active participle reduction'],['The equipment that is used for fermentation must be sterile.','USED','The equipment used for fermentation must be sterile','passive participle reduction'],['People who suffer from allergies should read every label.','SUFFERING','People suffering from allergies should read every label','active reduced clause'],['The bread that was baked at dawn remained warm.','BAKED','The bread baked at dawn remained warm','passive reduced clause'],['The next person who speaks will lose a point.','TO','The next person to speak will lose a point','infinitive after next'],['The spices that come from India are stored separately.','COMING','The spices coming from India are stored separately','present participle reduction'],['The invoice that was sent yesterday contains an error.','SENT','The invoice sent yesterday contains an error','past participle reduction']
]);

// VOCABULARY - 128.
function L(p,a,c,e){const g=Object.fromEntries(e.map(x=>[x[0],x[1]])),pool=[...new Set(e.map(x=>x[0]))];e.forEach(([ans,,s],i)=>{const al=pool.filter(x=>x!==ans),z=[];for(let k=0;k<al.length&&z.length<3;k++){const v=al[(i+k+1)%al.length];if(!z.includes(v))z.push(v)}while(z.length<3)z.push(['portion','plate','course','dish'].find(x=>x!==ans&&!z.includes(x)));unit9Questions.push(q(p+String(i+1).padStart(2,'0'),a,'Vocabulary',c,s,[ans,...z],ans,`precise ${c.toLowerCase()} usage`,'',g))})}
L('v1-','Vocabulary 1 - Eating and dining','Food & Drink',[
 ['appetite','apetito','The aroma immediately stimulated everyone’s ___.'],['cutlery','cubiertos','Place the clean ___ beside each plate.'],['digestion','digestión','Gentle movement after meals may aid ___.'],['nibble','mordisquear','She began to ___ a piece of cheese.'],['sip','sorber / tomar a pequeños tragos','He paused to ___ the hot broth.'],['straw','pajita / sorbete','The drink was served with a reusable ___.'],['portion','porción','The tasting menu includes a small ___ of each dish.'],['course','plato de una comida','Dessert was the final ___ of an elaborate meal.'],['serving','ración','Each ___ contains approximately two hundred calories.'],['leftovers','sobras','Refrigerate the ___ within two hours.'],['utensil','utensilio','Use a separate ___ for raw meat.'],['napkin','servilleta','She unfolded the linen ___ across her lap.']
]);
L('v2-','Vocabulary 2 - Food qualities','Food & Drink',[
 ['tender','tierno','The slow-cooked meat was exceptionally ___.'],['crisp','crujiente','The salad leaves remained fresh and ___.'],['soggy','empapado / blando','The pastry became ___ after being refrigerated uncovered.'],['stale','duro / pasado','The bread tasted ___ by the following morning.'],['bland','insípido','Without herbs, the soup seemed rather ___.'],['pungent','penetrante','The cheese has a powerful, ___ aroma.'],['succulent','jugoso','The roasted vegetables were sweet and ___.'],['rancid','rancio','Heat had caused the oil to turn ___.'],['zesty','cítrico / lleno de sabor','Lime gave the sauce a ___ freshness.'],['velvety','aterciopelado','The purée had a smooth, ___ texture.'],['tangy','ácido y sabroso','The yoghurt added a pleasantly ___ note.'],['charred','chamuscado','The peppers were lightly ___ over an open flame.']
]);
L('v3-','Vocabulary 3 - Cooking verbs','Food & Drink',[
 ['simmer','cocer a fuego lento','Allow the sauce to ___ gently for twenty minutes.'],['whisk','batir','___ the eggs until pale and airy.'],['grate','rallar','Finely ___ the cheese over the pasta.'],['dice','cortar en cubos','___ the vegetables into equal pieces.'],['knead','amasar','___ the dough until elastic.'],['marinate','marinar','___ the fish overnight with citrus and herbs.'],['poach','escalfar','The chef chose to ___ the pears in spiced syrup.'],['sear','sellar','___ the meat quickly on every side.'],['drizzle','rociar','___ olive oil over the finished dish.'],['garnish','decorar un plato','___ each bowl with fresh coriander.'],['ferment','fermentar','The mixture must ___ at room temperature.'],['puree','hacer puré','___ the roasted pumpkin until completely smooth.'],['blanch','escaldar','___ the beans briefly before cooling them.'],['braise','estofar','___ the beef slowly in a covered pan.']
]);
L('v4-','Vocabulary 4 - Ingredients','Food & Drink',[
 ['seasoning','condimento','Taste the sauce before adding more ___.'],['herb','hierba aromática','Basil is the dominant ___ in the dressing.'],['spice','especia','Cumin is a warm, earthy ___.'],['stock','caldo base','Use vegetable ___ as the base for the soup.'],['batter','masa líquida','Dip each piece into the light ___.'],['dough','masa','Leave the bread ___ to rise.'],['crumb','miga','Not a single ___ remained on the plate.'],['zest','ralladura','Add the grated ___ of one lemon.'],['pulp','pulpa','The juice retains some fruit ___.'],['kernel','grano / semilla','Each corn ___ was toasted.'],['peel','cáscara','The bitter ___ should be removed.'],['vinegar','vinagre','A splash of ___ balanced the sweetness.'],['yeast','levadura','Fresh ___ makes the dough rise.'],['flour','harina','Sift the ___ before mixing it.']
]);
L('v5-','Vocabulary 5 - Food phrasal verbs','Phrasal Verbs',[
 ['catch on','ponerse de moda','Plant-based tasting menus began to ___.'],['cater to','atender las necesidades de','The venue can ___ guests with allergies.'],['check out','probar / visitar','We decided to ___ the new bakery.'],['draw up','redactar','The dietitian will ___ a weekly meal plan.'],['feast on','darse un festín con','Visitors can ___ fresh seafood.'],['fix up','preparar','I can ___ a quick lunch.'],['go off','echarse a perder','Milk will ___ if left unrefrigerated.'],['heat up','calentar','Please ___ the soup before serving it.'],['live on','alimentarse principalmente de','Students cannot ___ instant noodles indefinitely.'],['polish off','terminar de comer rápidamente','They managed to ___ the entire cake.'],['rustle up','preparar rápidamente','She can ___ an impressive meal from scraps.'],['wash down','acompañar con bebida','He ___ the sandwich with cold juice.'],['cut up','cortar en trozos','___ the fruit before adding it.'],['pick at','comer sin ganas','The nervous diner merely ___ his food.']
]);
L('v6-','Vocabulary 6 - Food prepositions','Prepositions',[
 ['with','con','The tart is filled ___ seasonal berries.'],['in','en','The vegetables were cooked ___ olive oil.'],['into','en / dentro de','Fold the cream ___ the mixture carefully.'],['on','en / sobre','The restaurant specialises ___ coastal cuisine.'],['for','por','The region is renowned ___ its coffee.'],['from','de / a partir de','Traditional chicha is made ___ maize.'],['to','a','Add salt ___ taste.'],['of','de','The menu consists ___ seven small courses.'],['by','por','The dish was inspired ___ Andean traditions.'],['at','a','Bake the bread ___ a high temperature.']
]);
L('v7-','Vocabulary 7 - Culinary collocations','Collocations',[
 ['balanced diet','dieta equilibrada','Long-term health depends partly on a ___.'],['acquired taste','gusto adquirido','Fermented fish can be an ___.'],['hearty meal','comida sustanciosa','After the hike, everyone wanted a ___.'],['light snack','tentempié ligero','A ___ is available between sessions.'],['seasonal produce','productos de temporada','The restaurant prioritises ___.'],['locally sourced','de origen local','Every ingredient is ___.'],['fine dining','alta cocina','The hotel is known for ___.'],['food poisoning','intoxicación alimentaria','Poor refrigeration can cause ___.'],['special dietary requirements','necesidades dietéticas especiales','Tell us about any ___.'],['generous helping','porción abundante','The server gave us a ___.'],['signature dish','plato insignia','The ceviche is their ___.'],['packed lunch','almuerzo para llevar','Each participant should bring a ___.'],['comfort food','comida reconfortante','Soup is classic ___ during cold weather.'],['freshly ground','recién molido','The coffee is ___ for every cup.']
]);
L('v8-','Vocabulary 8 - Food idioms','Idioms',[
 ['slipped my mind','se me olvidó','Buying bread completely ___.'],['off the beaten track','fuera de la ruta habitual','The café is ___ but worth finding.'],['piece of cake','pan comido','Preparing the basic sauce is a ___.'],['not my cup of tea','no es de mi gusto','Raw oysters are ___.'],['spill the beans','revelar el secreto','Do not ___ about the surprise dinner.'],['take with a pinch of salt','tomar con cautela','You should ___ online diet claims.'],['have a lot on your plate','tener muchas responsabilidades','The head chef already ___.'],['sell like hot cakes','venderse muy rápido','The pastries ___ every morning.'],['the icing on the cake','la guinda del pastel','Winning the award was ___.'],['bring home the bacon','ganarse el sustento','The business finally began to ___.'],['full of beans','lleno de energía','The children were ___ after breakfast.'],['hard nut to crack','persona/problema difícil','The secret recipe is a ___.'],['in a nutshell','en pocas palabras','___, the concept combines tradition and science.'],['food for thought','motivo de reflexión','The documentary offered considerable ___.'],['sour grapes','despecho','His criticism sounded like ___.'],['walking on eggshells','andar con pies de plomo','Staff felt they were ___ around the temperamental chef.']
]);
L('v9-','Vocabulary 9 - Restaurant language','Fixed Expressions',[
 ['book a table','reservar una mesa','We should ___ for Saturday evening.'],['set the table','poner la mesa','Please ___ before the guests arrive.'],['clear the table','retirar la mesa','Staff began to ___ after dessert.'],['place an order','hacer un pedido','We are ready to ___.'],['split the bill','dividir la cuenta','The group agreed to ___.'],['service charge','cargo por servicio','A twelve per cent ___ is included.'],['compliments of the chef','cortesía del chef','The small appetiser was ___.'],['house speciality','especialidad de la casa','Ask the server about the ___.'],['fully booked','sin mesas disponibles','The restaurant is ___ tonight.'],['set menu','menú fijo','The weekday ___ offers excellent value.'],['wine list','carta de vinos','Could we see the ___?'],['last orders','últimos pedidos','The bell signals ___.']
]);
B('v10-','Vocabulary 10 - Food transformations','Vocabulary','Vocabulary Transformations',[
 ['I completely forgot to buy the ingredients.','MIND','Buying the ingredients completely slipped my mind','slip your mind'],['The restaurant is in an unusual location away from tourists.','TRACK','The restaurant is off the beaten track','off the beaten track'],['I do not particularly enjoy extremely spicy food.','TEA','Extremely spicy food is not my cup of tea','not your cup of tea'],['Do not reveal the secret recipe.','BEANS','Do not spill the beans about the secret recipe','spill the beans'],['Treat that extravagant health claim cautiously.','PINCH','Take that extravagant health claim with a pinch of salt','pinch of salt'],['The new pastries sold extremely quickly.','CAKES','The new pastries sold like hot cakes','sell like hot cakes'],['Receiving a Michelin star completed their success perfectly.','ICING','Receiving a Michelin star was the icing on the cake','icing on the cake'],['The documentary gives us something important to consider.','THOUGHT','The documentary gives us food for thought','food for thought'],['Put simply, fermentation transforms flavour.','NUTSHELL','In a nutshell fermentation transforms flavour','in a nutshell'],['The task was extremely easy for the experienced chef.','CAKE','The task was a piece of cake for the experienced chef','piece of cake'],['The main course is the dish for which the restaurant is famous.','SIGNATURE','The main course is the restaurant’s signature dish','signature dish'],['The waiter divided the cost equally among us.','BILL','The waiter helped us split the bill','split the bill']
]);

// ENGLISH IN USE - 32.
C('e1-','English in Use 1 - Word formation','English in Use','Word Formation',[
 ['The pastry’s distinctive shape makes it instantly ___.',['recognisable','recognitionful','recognisedly','recognisingness'],'recognisable','adjective formation'],['The filling traditionally contains finely ___ vegetables.',['chopped','choppingly','chopment','choppable only'],'chopped','past participle adjective'],['Its enduring ___ reflects strong regional identity.',['popularity','popularnessly','popularise','popularly noun'],'popularity','abstract noun'],['The recipe allows considerable ___.',['variation','varyment','variednessly','variationally noun'],'variation','noun formation'],['The pastry was originally a practical and ___ meal.',['portable','portability adjective','portingful','transportedly'],'portable','adjective suffix able'],['Modern versions show remarkable ___.',['diversity','diversely noun','diversification adjective','diversionaryness'],'diversity','abstract noun'],['The edges must be sealed ___.',['securely','secure adjective only','securityly','securedness'],'securely','adverb formation'],['The dish has achieved international ___.',['recognition','recognisable noun','recognisedly','recognisingment'],'recognition','noun formation']
]);
B('e2-','English in Use 2 - Transformations','English in Use','Advanced Structures',[
 ['The meal was far better than we had expected.','EXCEEDED','The meal exceeded all our expectations','exceed expectations'],['The chef refused to reveal how the sauce was made.','SECRET','The chef kept the method of making the sauce secret','keep secret'],['Nobody can equal her skill at making pastry.','MATCH','There is nobody to match her skill at making pastry','nothing/nobody to match'],['The restaurant became popular almost immediately.','CAUGHT','The restaurant caught on almost immediately','catch on'],['We should consider his recommendation carefully.','THOUGHT','We should give his recommendation careful thought','give thought to'],['The price includes dessert and coffee.','BARGAIN','Dessert and coffee are included in the bargain','into/in the bargain'],['The food festival occurs annually in September.','BASIS','The food festival takes place on an annual basis in September','on a basis'],['The entire dinner was paid for by the hotel.','HOUSE','The entire dinner was on the house','on the house']
]);
C('e3-','English in Use 3 - Multiple-choice cloze','English in Use','Multiple-choice Cloze',[
 ['British cuisine was once the laughing ___ of Europe.',['stock','supply','reserve','portion'],'stock','laughing stock'],['Contemporary chefs have earned international ___.',['acclaim','claiming','announcement','applause at'],'acclaim','international acclaim'],['Restaurants now ___ produce from nearby farms.',['source','originate them','extract at','derive themselves'],'source','source produce'],['The revival has gathered considerable ___.',['momentum','velocity of','speeding','impulse at'],'momentum','gather momentum'],['Traditional recipes have been given a modern ___.',['twist','turning on','bend','rotation at'],'twist','modern twist'],['Regional dishes now feature ___ on fashionable menus.',['prominently','dominantly thing','foremostly','principally noun'],'prominently','feature prominently'],['The change owes much to chefs willing to ___ convention.',['challenge','fight at','oppose against','compete convention'],'challenge','challenge convention'],['Diners have become increasingly ___.',['discerning','discerned by','discernible people','discerningly noun'],'discerning','discerning consumers']
]);
C('e4-','English in Use 4 - Open cloze','English in Use','Open Cloze',[
 ['British cooking has changed dramatically ___ recent decades.',['in','at','on','for'],'in','in recent decades'],['Chefs draw inspiration ___ many culinary traditions.',['from','of','at','with'],'from','draw inspiration from'],['Local ingredients are valued not only for freshness ___ also for sustainability.',['but','and only','than','as'],'but','not only but also'],['Some dishes date back ___ medieval times.',['to','at','from of','with'],'to','date back to'],['The emphasis is ___ quality rather than quantity.',['on','at','for','into'],'on','emphasis on'],['Diners are more adventurous ___ they once were.',['than','that','as from','to'],'than','comparative than'],['Restaurants compete with one another ___ attract skilled staff.',['to','for attracting','at','with'],'to','purpose infinitive'],['The result is a food culture ___ continues to evolve.',['that','where subject','whose','whom'],'that','defining relative clause']
]);

export const unit9Sections=[{track:'Grammar',count:unit9Questions.filter(x=>x.track==='Grammar').length,description:'Defining, non-defining, formal, quantified and reduced relative clauses.'},{track:'Vocabulary',count:unit9Questions.filter(x=>x.track==='Vocabulary').length,description:'Food & Drink vocabulary, cooking language, phrasal verbs, collocations and idioms with Spanish support.'},{track:'English in Use',count:unit9Questions.filter(x=>x.track==='English in Use').length,description:'C2 word formation, transformations, multiple-choice cloze and open cloze.'}];
