// Spanish glosses for C2 Booster vocabulary choices.
// Multiword items are translated by meaning, not word by word.
const es={
 'allegation':'acusación / alegación','argument':'argumento / discusión','message':'mensaje','statement':'declaración / afirmación','assurance':'garantía / seguridad','channel':'canal / vía','cliché':'cliché / tópico','dialect':'dialecto','dispute':'disputa / conflicto','groan':'gemido / quejido','memo':'memorando','plea':'súplica / petición urgente','proverb':'proverbio','refusal':'negativa / rechazo','reminder':'recordatorio','reproach':'reproche','tribute':'homenaje','voice':'expresar / voz','roughly':'aproximadamente','silently':'en silencio','ordinary':'común / corriente','caution':'advertir / cautela','utter':'pronunciar / decir','assert':'afirmar / hacer valer','lobby':'presionar / hacer lobby','notify':'notificar','reassure':'tranquilizar','coherent':'coherente','interactive':'interactivo','chatty':'conversacional / hablador','explicit':'explícito','implicit':'implícito','precisely':'precisamente','highly':'sumamente / altamente','truly':'verdaderamente','anyhow':'de todos modos',
 'act on':'actuar según / poner en práctica','turn down':'rechazar / bajar','make out':'distinguir / entender','set aside':'reservar / dejar de lado','answer back':'contestar de mala manera','answer to':'responder ante','back up':'respaldar / apoyar','get at':'querer decir / insinuar','bear with':'tener paciencia con','go into':'examinar / entrar en detalle','go on':'continuar','own up':'admitir / confesar','slip out':'escaparse / salir accidentalmente','stick up for':'defender','phase out':'eliminar gradualmente','turn over':'dar la vuelta / facturar','make up':'inventar / reconciliarse','break into':'irrumpir / entrar en un sector','break up':'separar / disolver','bring off':'lograr con éxito','call off':'cancelar','catch on':'ponerse de moda / entender','cut off':'interrumpir / cortar','drop off':'disminuir / dejar','give away':'revelar / regalar','lay off':'despedir por reducción de personal','live on':'vivir de / subsistir con','look over':'revisar','stand in for':'sustituir temporalmente','stand out':'destacar','stand up for':'defender','take to':'aficionarse / adaptarse a',
 'of':'de','at':'en / a','by':'por / mediante','from':'de / desde','on':'en / sobre','about':'sobre / acerca de','against':'contra','beyond':'más allá de','in':'en / dentro de','with':'con','for':'para / por','to':'a / hacia',
 'pay':'pagar / hacer (según expresión)','do':'hacer','set':'establecer / fijar','put':'poner','reach':'alcanzar / llegar a','broaden':'ampliar','make':'hacer / realizar','stark':'marcado / contundente','agreement':'acuerdo','career':'carrera profesional','salary':'salario','contract':'contrato','resignation':'renuncia','wrongful':'improcedente / injustificado','labour':'mano de obra / trabajo','promotion':'ascenso','rewarding':'gratificante','entry-level':'de nivel inicial','landed':'consiguió / obtuvo','living':'sustento / vida','minimum':'mínimo',
 'all things considered':'considerándolo todo','at random':'al azar','by mistake':'por error','in turn':'a su vez','all just the same':'aun así / de todos modos','be all set':'estar completamente listo','for one thing':'por una parte / para empezar','in a sense':'en cierto sentido','in all probability':'con toda probabilidad','in no uncertain terms':'de forma tajante / inequívoca','of its own accord':'por sí solo / espontáneamente','on hold':'en espera / suspendido','on no account':'bajo ninguna circunstancia','once and for all':'de una vez por todas','so to speak':'por así decirlo','take it from me':'créeme / hazme caso','in any case':'en cualquier caso','by and large':'en general / en líneas generales',
 'get it off your chest':'desahogarse / sacárselo de encima','lose the plot':'perder el hilo / descontrolarse','take a shortcut':'tomar un atajo','draw a blank':'quedarse en blanco','bone of contention':'motivo de disputa','beside herself with worry':'fuera de sí de preocupación','across the board':'de forma general / para todos','put you in the picture':'ponerte al corriente','on the ball':'atento / eficiente','for all intents and purposes':'a todos los efectos / prácticamente','speak volumes':'decir mucho / ser muy revelador','inside out':'al dedillo / de cabo a rabo','out of bounds':'fuera de límites / prohibido','out of the question':'fuera de toda posibilidad','back in the black':'de nuevo con beneficios','of all people':'precisamente tú/él/ella','tighten your belt':'apretarse el cinturón','before you know it':'antes de que te des cuenta','clear the air':'aclarar las cosas / aliviar la tensión','break the ice':'romper el hielo','read between the lines':'leer entre líneas','get your point across':'hacer entender tu punto de vista',
 'boardroom':'sala de juntas','position':'puesto / posición','task':'tarea','office':'oficina','casual':'informal','counterpart':'homólogo / contraparte','dismissal':'despido','enterprise':'empresa / iniciativa','establishment':'establecimiento / institución','mission':'misión','overloaded':'sobrecargado','overworked':'con exceso de trabajo','stock':'acciones / existencias','takeover':'adquisición / toma de control','turnover':'rotación / facturación','vacancy':'vacante','venture':'empresa / proyecto arriesgado','vocation':'vocación','adviser':'asesor','archaeologist':'arqueólogo','counsellor':'orientador / consejero','developer':'desarrollador','executive':'ejecutivo / directivo','jobseeker':'persona que busca empleo','miner':'minero','official':'funcionario / representante oficial','personnel':'personal','recruit':'nuevo empleado / recluta','solicitor':'abogado','striker':'huelguista','successor':'sucesor','supervisor':'supervisor','technician':'técnico','trainee':'aprendiz / empleado en formación',
 'spoilt for choice':'tener demasiadas buenas opciones','under pressure':'bajo presión','in charge':'a cargo','at work':'en el trabajo','feel it in my bones':'presentirlo / sentirlo profundamente','rings a bell':'me suena / resulta familiar','on the line':'en riesgo','makes my blood boil':'me hace hervir la sangre / me enfurece','break even':'quedar sin pérdidas ni ganancias','broke':'sin dinero / quebrado','out of the blue':'de la nada / inesperadamente','hold down':'mantener (un empleo)','carries weight':'tener peso / influencia','best of both worlds':'lo mejor de ambos mundos','on track':'bien encaminado','in safe hands':'en buenas manos','red tape':'burocracia / papeleo excesivo','climb the ladder':'ascender profesionalmente','learn the ropes':'aprender cómo funciona el trabajo',
 'labour market':'mercado laboral','career path':'trayectoria profesional','working day':'jornada laboral','pay rise':'aumento de sueldo','living wage':'salario digno','steady job':'trabajo estable','menial work':'trabajo servil / poco cualificado','might as well':'más vale / podríamos igualmente','make her way':'abrirse camino','internship':'prácticas profesionales','out of a job':'sin trabajo','skeleton crew':'personal mínimo indispensable','gap in the market':'nicho / oportunidad en el mercado','hanging in the balance':'pendiente de un hilo / sin decidir','hand in my notice':'presentar mi renuncia / preaviso','career change':'cambio de carrera profesional','work overtime':'trabajar horas extra','target market':'mercado objetivo','on the panel':'en el comité / jurado'
};

export function spanishGloss(text){return es[text.toLowerCase().trim()]||''}
